- android/src/main/java/com/AirMaps/AirMapManager.java
- android/src/main/java/com/AirMaps/AirMapView.java
- components/MapView.js
to: @christopherdro 
Please try this locally. I did a couple of goofy things to the project files to get this running locally that i didnt commit. Project needs a new .gitignore...
> Refactored AirMapView to use getMapAsync

- example/package.json
- ios/AirMaps.xcodeproj/project.pbxproj
- ios/AirMaps/AIRMapCircle.m
- ios/AirMaps/AIRMapPolygon.m
> Fixed RCTImageLoader issue

- components/MapMarker.js
- example/App.js
- example/examples/AnimatedMarkers.js
> Animated Marker Position

- README.md
- android/src/main/java/com/AirMaps/AirMapManager.java
- android/src/main/java/com/AirMaps/AirMapMarker.java
- android/src/main/java/com/AirMaps/AirMapMarkerManager.java
- android/src/main/java/com/AirMaps/AirMapView.java
- components/MapMarker.js
- components/MapView.js
- docs/mapview.md
- docs/marker.md
- example/App.js
- example/examples/DraggableMarkers.js
- example/ios/AirMapsExplorer.xcodeproj/project.pbxproj
- example/ios/AirMapsExplorer.xcodeproj/xcshareddata/xcschemes/AirMapsExplorer.xcscheme
- example/ios/AirMapsExplorer/Info.plist
- example/ios/AirMapsExplorerTests/Info.plist
- example/package.json
- ios/AirMaps.xcodeproj/project.pbxproj
- ios/AirMaps/AIRMap.h
- ios/AirMaps/AIRMap.m
- ios/AirMaps/AIRMapManager.m
- ios/AirMaps/AIRMapMarker.h
- ios/AirMaps/AIRMapMarker.m
- ios/AirMaps/AIRMapMarkerManager.m
- ios/AirMaps/AIRMapPolyline.m
- ios/AirMaps/Callout/SMCalloutView.h
Draggable Marker implementation
cc: @christopherdro
> Draggable Markers

- example/App.js
- example/examples/Callouts.js
- ios/AirMaps/AIRMapManager.m
- ios/AirMaps/AIRMapMarker.h
- ios/AirMaps/AIRMapMarker.m
- ios/AirMaps/AIRMapMarkerManager.m
Fixes #27 
This bug was was two-fold: pin views were always broken, and it looks like the callout views were broken since i added in the SMCalloutView library.
This should fix it!
> Fix showCallout bug for pin views on ios

- components/MapCircle.js
- components/MapPolygon.js
- components/MapPolyline.js
- docs/circle.md
- docs/polygon.md
- docs/polyline.md
- example/App.js
- example/examples/Overlays.js
- ios/AirMaps/AIRMapCircle.h
- ios/AirMaps/AIRMapCircle.m
- ios/AirMaps/AIRMapCircleManager.m
- ios/AirMaps/AIRMapPolygon.h
- ios/AirMaps/AIRMapPolygon.m
- ios/AirMaps/AIRMapPolygonManager.m
- ios/AirMaps/AIRMapPolyline.h
- ios/AirMaps/AIRMapPolyline.m
- ios/AirMaps/AIRMapPolylineManager.m
Fixes #33 
http://i.imgur.com/zyI8Fuh.png
> Add dashed line support for iOS

- docs/installation.md
- example/examples/DraggableMarkers.js
> [Docs] Update Android installation to reflect new versions of RN. 

- README.md
> Update Readme to indicate version compatibility

- android/src/main/java/com/AirMaps/AirMapManager.java
- android/src/main/java/com/AirMaps/AirMapView.java
PR regarding memory leak reported at https://github.com/lelandrichardson/react-native-maps/issues/95
implementation shows an improvement but still does not seem to cover the issue completely.
> forward onDestroy when removing view

- README.md
Hello,
I had some lines in the Readme file, to explain the styles needs of the `MapView`. Because the first time I install `react-native-maps`, I had a blank view and I don't really understand why.
So add some lines can really help for future users :) 
Regards,
Jérémy Magrin
> Add some lines in Readme, to explain the styles needs of the MapView (blank-view)

- android/src/main/java/com/AirMaps/AirMapManager.java
- components/MapView.js
- docs/mapview.md
Continuation of [#80](https://github.com/lelandrichardson/react-native-maps/pull/80)
> (Android only) add terrain map type

- docs/installation.md
Hello,
As requested here : #176, I updated the docs with a troubleshooting section for the blank map issue.
Thank's
> Added troubleshooting for the blank map issue

- android/src/main/java/com/AirMaps/AirMapMarker.java
See [CodePush issue 198](https://github.com/Microsoft/code-push/issues/198).
> Add support for file://-based assets

- docs/installation.md
The `src` folder is located inside `android/app`. Made this update in installation instructions.
> Update android folder structure in installation.md

- docs/mapview.md
I missed something in my previous PR (#212). This fixes it.
> Fix docs for `showsUserLocation`

- docs/installation.md
> Fixes wrong jar version in instructions

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapView.java
> Fix: Map not removing markers and other features causing memory leak

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- android/lib/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
- docs/installation.md
- example/android/app/src/main/java/com/airbnb/android/react/maps/example/MainActivity.java
Taken from https://github.com/lelandrichardson/react-native-maps/pull/276
> Use ReactActivity in AirMapView

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
> Fix custom marker anchor points

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- components/MapView.js
- docs/mapview.md
Resolves [#158](https://github.com/lelandrichardson/react-native-maps/issues/158)
> made android maps toolbar controllable by prop

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapView.java
@lelandrichardson && @jrichardlai this is the same issue mentioned in #64 , it turns out that this is a known bug in MapView i just implemented the fix suggested on [stackoverflow]: http://stackoverflow.com/questions/6546108/mapview-inside-a-scrollview
Already tested this solution on another project and it works perfectly!
> Fixing scrolling map inside a scrollView

- docs/installation.md
- example/android/app/build.gradle
This seems to be causing a lot of confusion
@lelandrichardson @christopherdro
> Update the Android installation instructions

- android/lib/build.gradle
- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- example/examples/AnimatedPriceMarker.js
- example/examples/PanController.js
- example/package.json
- package.json
> Fixes example JS code for RN 29 compatibility

- example/package.json
- example/scripts/watch-and-copy-src.js
* Add proper `devDependencies` to `package.json`
* Also watch and copy ios, android source code
to: @lelandrichardson
> Improvements to watch and copy script

- README.md
https://github.com/facebook/react-native/blob/8eed600d5b2be78c405f7ef139a7b0e4a2480c85/Libraries/StyleSheet/StyleSheet.js#L108
> absoluteFillObject

- .travis.yml
Add `.travis.yml` in order to run ESLint on PRs.
I'm not that familiar with Travis, so LMK if I'm doing anything wrong.
to: @lelandrichardson @christopherdro
> Add .travis.yml to run ESLint

- CHANGELOG.md
- android/gradle.properties
- example/android/build.gradle
- example/android/gradle/wrapper/gradle-wrapper.properties
- package.json
- react-native-maps.podspec
> Prepare for release v0.8.1

- docs/mapview.md
add missing showsMyLocationButton props of MapView in docs.
> add missing showsMyLocationButton in docs

- docs/mapview.md
Clarified the difference between onRegionChange and onRegionChange
notes for each match comments in MapView.js
> Updated Mapview onRegionChange events notes

- docs/installation.md
Add relative links to point at repo's example Podfile
> Add relative links to Podfiles

- ios/AirMaps/AIRMapManager.m
Introduced in https://github.com/airbnb/react-native-maps/pull/615
to: @gilbox @IjzerenHein
> Fix import of AIRMapSnapshot

- docs/installation.md
Streamlines installation process and improves formatting.
> improve installation instructions

- react-native-google-maps.podspec
> Fix podspec github url

- ios/AirGoogleMaps/AIRGoogleMap.m
This effects events on iOS: the `onRegionChange` event as well as `onRegionChangeComplete` (the latter is currently only available with google).
@spikebrehm @lelandrichardson
> [google][ios] Make provider="google" use same region format as MapKit

- ios/AirMaps/AIRMapMarker.m
Signature changed here:
https://github.com/facebook/react-native/commit/820b1c0e46f781f6677caa3a62b59076bf2700e5
> change loadImageWithURLRequest for RN 0.35

- example/ios/Podfile.lock
- example/package.json
- ios/AirMaps/AIRMapMarker.m
- package.json
> Bump RN version to 0.33.0

- ios/AirGoogleMaps/AIRGoogleMap.h
- ios/AirGoogleMaps/AIRGoogleMap.m
- ios/AirGoogleMaps/AIRGoogleMapManager.m
Implements [animateToRegion](https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md#methods) on Google Maps iOS
Factorize as static methods of `AIRGoogleMap`:
- `makeMKCoordinateRegionFromGMSCameraPositionOfMap` 
- `makeGMSCameraPositionFromMKCoordinateRegionOfMap`
> [Google Maps iOS]Implements animateToRegion

- android/build.gradle
update google play services for better compatiblity
for this issue
[https://github.com/airbnb/react-native-maps/issues/804](url)
#804
> update google play services

- README.md
- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- components/MapView.js
- example/App.js
- example/examples/MapStyle.js
This pull request is to separate the styling into a separate pull request from #670.
I don't have access to a mac now so I'll create another pull request for ios by monday. But this code should compile normally on ios, but the map won't be styled.
> Map Styling for android

- example/ios/Podfile
In order to prevent support requests like #830
> Added more help to the Podfile.

- docs/installation.md
- Updated descriptions of getting and using Android API Keys.  It works differently than when this was originally written.
- Added fix if DexException encountered
- Added "import" in map component code
- Other small changes
> Updated install documentation after successfully getting iOS and Android working

- docs/installation.md
- react-native-google-maps.podspec
- afaik `GMSMapStyle` is not present in 2.0.x
I've opened issue #899.
> fixes Option 2 building

- docs/polyline.md
Fix the minor error: polygon => polyline
> Update doc for polyline

- docs/installation.md
> Update doc to show how to add GoogleMaps support for iOS.

- components/MapView.js
DRY it up and simplify.
to: @gilbox @lelandrichardson
> Clean up MapView#_onLayout a bit.

- README.md
- docs/mapview.md
Readme addition described in https://github.com/airbnb/react-native-maps/issues/881.
> Improve documentation of customMapStyle

- android/build.gradle
Updated Google play services to v10.0.1 and updated the gradle build plugin to 2.2.3
> Updated Google play services and gradle build plugin

- docs/circle.md
- docs/polygon.md
Courtesy of https://github.com/airbnb/react-native-maps/issues/183
> Mention rgba option for polygons in docs

- docs/installation.md
https://github.com/airbnb/react-native-maps/issues/1067 this is a common issue people are experiencing right now
> Update for dependency issues

- docs/installation.md
Add clarification to iOS options section that the advanced options may not be necessary.
> Add iOS tip

- example/App.js
- example/examples/BugMarkerWontUpdate.js
- example/examples/MyLocationMapMarker.js
- example/package.json
Created an example to expose this android bug.
> [android] Create example for marker not updating bug

- lib/android/build.gradle
> Upgrade GMS dependencies to 10.2.0

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
> Fix getResources() null crash in mapview

- docs/installation.md
I was having trouble compiling the android version but updating the project directory resolved it for me.
> Update path in android installation

- docs/mapview.md
- docs/marker.md
> Update docs to specify how to access event data

- docs/installation.md
I think the android folder moved:
`../node_modules/react-native-maps/android` => `../node_modules/react-native-maps/lib/android`
> Fixed path in `android/settings.gradle`

- docs/installation.md
the path to project dir is no longer up-to-date
> fixing code snippet

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
> Fix overlay issues in Android introduced in 0.13.1

- package.json
Overlooked this change closing out a few PR's last week.
Follow up for #1200
> [rnpm] Fix sourceDir for Android

- lib/ios/AirGoogleMaps/AIRGMSPolygon.h
Fix compile error in rn version >= 0.40
> fix compile error in rn version >= 0.40

- .idea/codeStyleSettings.xml
- build.gradle
- example/android/app/build.gradle
- example/android/app/src/main/java/com/airbnb/android/react/maps/example/MainActivity.java
- gradle/wrapper/gradle-wrapper.properties
- lib/android/build.gradle
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapCallout.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapCalloutManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapCircle.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapCircleManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapFeature.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapLiteManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolygon.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolygonManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolyline.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolylineManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapUrlTile.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapUrlTileManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/android/src/main/java/com/airbnb/android/react/maps/LatLngBoundsUtils.java
- lib/android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
- lib/android/src/main/java/com/airbnb/android/react/maps/RegionChangeEvent.java
- lib/android/src/main/java/com/airbnb/android/react/maps/SizeReportingShadowNode.java
Add IntelliJ code style settings, reformat everything
> [Android] Code cleanup step I - reformatting

- package.json
Required to use react-native >= 0.43
@lelandrichardson is anything else required to your knowledge?
> Allow react 16.0.0-alpha

- lib/ios/AirMaps/AIRMap.h
- lib/ios/AirMaps/AIRMap.m
- lib/ios/AirMaps/AIRMapManager.h
- lib/ios/AirMaps/AIRMapManager.m
> Zoom level fixes

- example/ios/Podfile
Just a quick update to the Ruby syntax on the Podfile.
> Enhance Podfile

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
Fix https://github.com/airbnb/react-native-maps/pull/1546 which was not working on Android
> Fix initial region android

- docs/circle.md
lineJoin : wrong type
lineCap : add  other values
> fixe mistakes on circle.md

- lib/ios/AirMaps/AIRMapManager.m
Fixes set initial region for ios and closes #1577
> Set initial region on view

- index.d.ts
> Added style prop to MapCalloutProps in Typings

- docs/installation.md
If the files are not copied during dragging the folder, your iOS
project will fail to build
> Added explicit instructions to copy `AirGoogleMaps` files

- CHANGELOG.md
Ignore this if the changelog is generated from commits or something.
> Update CHANGELOG.md to point to the correct PR url regarding TS definitions. 

- example/ios/AirMapsExplorer.xcodeproj/project.pbxproj
- example/ios/Podfile
- example/ios/Podfile.lock
fixes #1548 
Podfile.lock and AirMapsExplorer.xcodeproj/project.pbxproj are generated using pod install (1.3.1)
> Fixed Podfile so the project will contain necessary dependancy

- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
> Add missing parameters to IOS googlemaps snapshot

- README.md
I faced a similar problem of blank map but when I looked into Developer console I had not enabled the Google Maps API. After enabling the API, I ran the application on my android device and it worked. 
So, you need to enable Google maps API in the google developer console for android/ios. I would be happy if you could assign `hacktoberfest` label to this PR :)
> Blank map issue: Google Maps API not enabled?

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
> [AirMapView] Null check map instance on view methods

- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
> fix 1690. Add requiresMainQueueSetup

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
> Fix 1153 (Not a ViewGroup element cast to ViewGroup)

- docs/installation.md
This should address https://github.com/react-community/react-native-maps/issues/1862
> [WIP] Fix main docs

- docs/installation.md
Fixed minor styling issues per discussion in #1862
> Updated styling in installation guide

- .github/ISSUE_TEMPLATE.md
It seems that some people still don't use the template, so moved the warning on top and made it a little more aggressive :)
> Update issues template with no_template warning

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
Added `import com.facebook.react.bridge.WritableNativeMap;`
> Add missing import on AirMapModule.java

- docs/polygon.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolygon.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolygonManager.java
Support Android polygon holes.
Duplicated issue with #1271.
> Android polygon holes support

- example/App.js
- example/examples/ImageOverlayWithAssets.js
- example/examples/ImageOverlayWithURL.js
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlay.java
- lib/android/src/main/java/com/airbnb/android/react/maps/ImageReadable.java
- lib/android/src/main/java/com/airbnb/android/react/maps/ImageReader.java
- lib/components/MapOverlay.js
Update for #1918, see my comment at #1359 
- fix LatLngBounds order
- LatLngBounds use Double instead of String
- enable to image readable and support URI
- added two examples
@rborn please review it.
also, ping @MartynasZilinskas
> Fix Map.Overlay for android

- index.js
> fix module undefined bug in react-native@0.54.0 (#2051)

- docs/installation.md
- example/ios/Podfile
No
Installation error on the `pod install` step with the current PodFile on the docs/installation.md
https://github.com/react-community/react-native-maps/issues/2063
> removed BatchedBridge from docs/installation.md

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a new question to the pull request template:
> ### How did you test this PR?
> 
>
> Please let us know how you have verified that your changes work.
> 
> Ideally, your PR should contain a step-by-step test plan, so that reviewers can easily verify your changes.
> 
> Your PR will have much better chances of being merged if it is straightforward to verify.
> 
> Some questions you might want to think about:
> 
> - Which platform (eg. Android/iOS) & Maps API (eg. Google/Apple) does this change affect, if any?
> - Did you test this on a real device, or in a simulator?
> - Are there any platforms you were not able to test?
This should make it much easier for reviewers to figure out what needs to be verified :)
I additionally rephrased one of the questions to be a bit clearer & …
> Add testing section to pull request template & tighten up question copy.

- index.d.ts
No
#2112
Compiled from a separate RN project using the locally-updated node module. There doesn't appear to be any actual TypeScript code in the repo to test.
> Fix a few typescript declarations

- lib/ios/AirGoogleMaps/AIRGoogleMap.m
See https://github.com/react-community/react-native-maps/issues/2100 for discussion.
> Fix initialRegion when using RN 0.54

- docs/marker.md
No.
No issue, just extended the API docs with the undocumented `opacity` property.
Checked the API docs.
> Add opacity to API docs.

- lib/ios/AirGoogleMaps/AIRGoogleMap.m
Not that I'm aware of
Make imports for files in Google-Maps-iOS-Utils use global import notation. This helps with versioning this library in Expo.
Installed this library on a clean RN project, made changes to AIRGoogleMap.m file, pod install, built Xcode project successfully
> use global imports for new Pods dependencies in AIRGoogleMap

- lib/ios/AirMaps/AIRMap.m
No
https://github.com/react-community/react-native-maps/issues/2153
Building the project with the build warning `CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF` turned on.
> Fix CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF warnings

- package.json
No.
#2264 
Installing react-native-maps with this patch applied in an app with `react-native@0.55.4` and `react@16.3.1` as dependencies.
With this patch applied, the following install error is no longer present.
```
npm WARN react-native-maps@0.21.0 requires a peer of react-native@^0.51 || ^0.52 || ^0.53 || ^0.54 but none is installed. You must install peer dependencies yourself.
npm ERR! Cannot read property '0' of undefined
```
> Add react-native@^0.55 to peerDependencies

- docs/mapview.md
Formatting issue in the readme
(No issue, just noticed it so fixing it)
With my eyes ;)
> Fix readme formatting

- docs/installation.md
No
Confusing/wrong/improvable formatting, indentation and syntax highlighting in the docs.
Read the doc and check it is still legible.
> Update installation docs

- docs/installation.md
No.
Issue #2362 
Installation docs do not mention that `{PROVIDER_GOOGLE}` needs to be added in order to make Google Maps work on iOS. This PR adds the required lines to make Google Maps work on iOS.
This is an update to the documentation only.
> Specify how to use Google Maps

- CHANGELOG.md
- example/ios/Podfile.lock
- lib/android/gradle.properties
- package.json
> [0.22.1] Release

- docs/installation.md
Important note for Google Play Services when conflicting with other modules
> Adding notes for Google Play Services

- lib/components/MapMarker.js
- lib/components/MapOverlay.js
Not that I know of.
#2454
#2453
PR fixes compatibility issue with 'react-native-web' and compiling.
Compiled successfully on Windows & OSX for Android & IOS.
> fix import error on compilation

- docs/installation.md
No
#2636
Only changes documentation, no tests needed.
> add note about recursive framework search paths

- example/ios/Podfile
No
#2380 
At first I had the same problem as issue #2380. After the path was changed, I am able to build example project successfully and run on simulator.
> Fix path for yoga in Podfile

- docs/mapview.md
No, it's a documentation problem for which an issue has been created some time ago.
https://github.com/react-native-community/react-native-maps/issues/637
Added some documentation on latitudeDelta and longitudeDelta
No need for testing md changes of course
> Improved mapview doc for delta properties

- index.d.ts
No
Add typings for existing methods that can be used in Typescript.
Follow the format declared at [doc](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md)
> add typings for pointForCoordinate & coordinateForPoint

- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
YES, 2446
merge conflict in 2446
> Fix iOS GoogleMap update camera always animated

- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
rebasing https://github.com/react-native-community/react-native-maps/pull/2314 on master before testing and merging
> Adding onPanDrag compatibility for iOS

- docs/mapview.md
- lib/components/MapView.js
> Indicat that showsScale prop is Apple Maps only

- CHANGELOG.md
No.
Links to PRs in `CHANGELOG.md`.
Manually checking the links.
> Fix PR links in CHANGELOG.md

- docs/marker.md
I literally just trial and errorred this after banging my head.
> Note that children components can be added

- lib/ios/AirGoogleMaps/AIRGoogleMap.m
Fixes memory leak on iOS Google Maps (appeared after #2581)
Should resolve issues #2782 and #2775
Before:
After:
> [AIRGoogleMap] Fixed memory leak

- docs/overlay.md
No
https://github.com/react-native-community/react-native-maps/issues/2715
Documentation change based on finding the current docs don't correctly describe the true implementation steps. (or at least are confusing)
Small change to better explain the true implementation of the `Overlay` `bounds` prop.
> Documentation: Clarify Overlay component bounds prop

- index.d.ts
no
#2827
installed my fork in my project.
> * getMapBoundaries really returns a Promise

- docs/installation.md
> fixed android installation instruction

- lib/components/MapView.js
> Remove componentWillUpdate

- docs/installation.md
Update for React Native 0.60+
No issues, just an update
> Update installation.md for RN 0.60+

- docs/installation.md
Removed dangling back-ticks that caused the json section to be displayed incorrectly
No
This is just a documentation change, i verified the github markdown parser displays the file correctly by using the previewer.
The preview can be used to see the performed fixes.
> Remove dangling back-ticks to fix code sections

- react-native-google-maps.podspec
No.
Bug when rerendering polygons.
https://issuetracker.google.com/issues/130331383
I tested it by changing the node_modules in my project and the bug was fixed on iOS. The bug didn't occur on Android.
> Update GoogleMaps pod to 3.2.0

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
Couldn't find one that does the same.
This PR is helping add future support to turbomodules processor by adding @ReactModule annotation. Inspired by @janicduplessis on [this](https://github.com/timfpark/react-native-location/pull/79/files) PR and [this](https://twitter.com/janicduplessis/status/1157152160972333058) twitter thread.
- Which platform? Android
- Did you test this on a real device, or in a simulator? Tested on a real device.
- Are there any platforms you were not able to test? Only Android suffered modifications.
> Add @ReactModule annotation to help turbomodules processor

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
No
#3031
Such simple NPE protection doesn't need testing.
> Fixes NPE while removing already removed marker.

- README.md
developer console link now open
https://console.developers.google.com/
> readme.md file  change developer console link now open

- docs/installation.md
I had a quick search and couldn't find it.
None.
It's only fixing a typo in the docs.
> Fix typo in installation.md with word `Android`

- lib/ios/AirMaps/AIRMapOverlay.m
Yes - PR from https://github.com/react-native-community/react-native-maps/issues/2801
has been merged, but there are still error in it
same as:
https://github.com/react-native-community/react-native-maps/issues/2801
ran it on iOS and Android deviced
> fix overlay sizing

- react-native-google-maps.podspec
> Fix iOS Marker Titles in Dark Mode

- docs/geojson.md
> Add missing props to Geojson documentation

- index.d.ts
Didn't find any open analogous PRs
Didn't find any open issues about this inconsistence
I've just applied this patch directly in my `node_modules` and run `tsc`. And checked if VisualStudio Code renders the doc correctly:
> Add `Marker.redraw()` method to TypeScript typings

- react-native-google-maps.podspec
- react-native-maps.podspec
Add tag to avoid bug (install from master branch) when install with :podspec instead :path 
> Fix podspec to install from :podspec (install pod, not development pod)

- docs/installation.md
There's no other similar PR
App crash before map rendering
**RN 0.61.5**
**Android 9 Pie**
**Exception:** Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion"
I build the application on a real Android 9 Pie device, on developer mode.
The application did no crash anymore.
> Add manifest requirement for RN 0.61.5

- docs/installation.md
Added a default playServicesVersion and showed how to find latest version in installation docs.
Every time I use this package I have to check what a valid playServicesVersion is otherwise it doesn't compile. I figured I would make it easier for others who have the same issue.
No
#3116 
I read through it and checked the link works.
As for version 17.0.0, have tested on a real device, simulator, Nexus 2nd Gen, Samsung J5, S5, A30, iPhone XR
> Changes to playServicesVersion on installation docs

- lib/android/src/main/java/com/airbnb/android/react/maps/FusedLocationSource.java
No
#3344 
Tested on Android Emulator w/ Detox on a CI server where this was previously occurring. The crash does not recur.
> Protect against null Location in FusedLocationSource

- example/android/app/build.gradle
- example/examples/ViewsAsMarkers.js
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
This reverts commit 27c0e60b6c007819ef99523fcd7f8b1704ecb5f5.
PR #3035
> Revert "android google map callout support <Image/> (#3035)"

- docs/mapview.md
- index.d.ts
As far as I know no other currently open pr addressed these issues. They are very minor, but we still consider them to be nice for QoL ( auto-completion :) )
While working on a react-native typescript project for one of our classes, we noticed that some of the type definitions and documentation were either missing or wrong. This pr aims to fix these minor issues.
Issue #: #3353
You can follow the steps outlined in the #3353 issue, but I will repeat them here.
1. Expo init a new project with typescript
2. Copy-paste the content of the IndoorMap.js example code into App.tsx.
3. Run npm install react-native-maps
4. You should now no longer have issues with typescript for onIndoorBuildingFocused() and setIndoorActiveLevelIndex()
Additionally, here is a screenshot of the IndoorBuildingEvent …
> Include missing type definitions and fix readme

- package.json
- yarn.lock
No
This is the fix for a review on PR #3331 
I tested it by running `tsc`. The reported error doesn't show up anymore
> Added @types/geojson to devDependencies

- index.d.ts
No, not as far as I can tell.
Fixes type definitions and documentionation for the `MapView` component.
Manually tested with vscode.
> Include missing location type definitions

- lib/components/Geojson.js
- lib/components/MapPolygon.js
No
#3352 
I verified that I no longer get the warning messages in the console. I was only able to test this on an android emulator, but its a pretty minimal javascript change, so I would assume it would work on iOS as well.
> Bugfix for the "require cycles" warning

- lib/components/MapView.web.js
- package.json
- https://github.com/expo/expo/issues/8585
- I eyeballed it
> [web] Added basic shim to prevent crashing

- example/android/app/src/main/AndroidManifest.xml
- gradle.properties
Applies https://github.com/react-native-community/react-native-maps/issues/3448
This merge request solves the issue with example app with this setup.
Tested on a simulator.
Not sure if it's favoured way to fix that by enabling Jetifier and AndroidX.
> Android: Fix build for example app

- docs/installation.md
No
Fixing a typeo where the docs were referencing a version (10.0.1) which doesn't exist anymore.
I read through the new docs
> Fixed version discrepancy

- docs/installation.md
No, not right now in opened PRs.
Updating troubleshooting information.
Just updated an installation.md file to prevent confusion.
> Add missing res folder in INSTALLATION.md

- docs/mapview.md
Not that I know of.
Syntax error
VSCode accepted the solution
> Added necessary commas where missing.

- .travis.yml
- lib/components/AnimatedRegion.js
- yarn.lock
Should fix travis https://github.com/react-native-maps/react-native-maps/issues/3565
> Fix for build fail #3565

- .travis.yml
- lib/components/AnimatedRegion.js
- react-native-google-maps.podspec
- react-native-maps.podspec
- yarn.lock
No.
The latest Xcode 12 fails to build when a module does not depend on `React-Core` directly. This change is necessary for all native modules on iOS. For details please see: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
1. Build an App with Xcode 11.x. Result: The app builds.
2. Build an App with Xcode 12. Result: The app will not build when depending on `React`.
3. Build an App with Xcode 12 with the PR changes applied. Result: The app builds.
> fix: Xcode 12 compatibility

- index.d.ts
- lib/components/MapView.js
not afaik
making #3383 accessible from javascript
ran in my app, changed the tint color, saw the new color on iOS
> adds javascript binding for MapView.tintColor

- index.d.ts
- lib/components/Geojson.js
No
While the Polyline component already had props for rendering dashed and dotted lines, the Geojson component, despite using Polyline component, didn't have those. So I provided these props (lineDashPhase, lineDashPattern, lineCap, lineJoin and miterLimit) to Geojson.js, so that they can be accessible from the component itself.
This change has been tested on both Android and iOS, using Google Maps API on an LG Nexus 5 real device (android 6.0.1), and using Apple maps API on an iPhone simulated device, running iOS 13.
> Added polyline props to obtain dashed/dotted lines in Geojson component

- lib/components/MapView.js
No
No open issue, but this fixes the fact that it was impossible to perform direct manipulation on the MapView component (which is useful in some cases for performance reasons), even though other components, like Marker, allow this.
I've tested this on a physical iOS device, by creating a MapView component and doing direct manipulation on the camera property.
> Add the ability to call setNativeProps on MapView component

- docs/geojson.md
No
Geojson component documentation was missing some props 
Well it's just documentation but I also checked that the props were actually there (Android device with Google maps).
> update Geojson component docs

- lib/android/src/main/java/com/airbnb/android/react/maps/FusedLocationSource.java
No
[#3162 ](https://github.com/react-native-maps/react-native-maps/issues/3612)
This change was tested in multiple Android Devices and Emulators.
> Added try and catch clause in the activate method to aviod build errors.

- README.md
> Remove doc related to very old RN versions which is no longer supported

- docs/mapview.md
No, this PR is for an unidentified Documentation error.
This PR is in accordance to the issue  #3714
I've tested this while running it on my project using react-native-maps
> Update mapview.md for Documentation Change to fix the issue 

- docs/overlay.md
- example/App.js
- example/examples/ImageOverlayWithBearing.js
- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlay.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlayManager.java
- lib/components/MapOverlay.js
- lib/ios/AirGoogleMaps/AIRGoogleMapOverlay.h
- lib/ios/AirGoogleMaps/AIRGoogleMapOverlay.m
- lib/ios/AirGoogleMaps/AIRGoogleMapOverlayManager.m
#3214 (outdated, Dec 2019)
- Skipped width, height and anchor implementation as it is Android specific
- Improved documentation (again, skipped width, height and anchor)
#2892
#2850
This feature is Google Maps only. I tested it with the example app in this repo on Android, as well as in my personal project (TraceForce) on both platforms.
> Image overlay rotation/bearing

- docs/geojson.md
- lib/components/Geojson.js
I could not find any other PR to do the same thing. 
#3727 
- I tested this PR on both Android and iOS.
- Tested on both simulator and real devices
> feat: Geojson marker has the onPress functionality now

- example/examples/WMSTiles.js
- index.d.ts
- lib/ios/AirMaps/AIRMap.m
None that I was able to find with search.
Issues #3719 and #3720. 
For issue #3720 which impacts only iOS & default Mapview (AirMaps):
1. I updated WMSTiles.js example (which seemed anyways out of date as I could not see any data from the WMS-tileserver) to have a WMS-tileserver that provides meaningful data and also added functionality to toggle on & off WMSTile-layer to the text bubble on the bottom of the screen.
2. I tested with the new WMSTiles.js example behaviour of WMSTile-component on iOS simulator to verify that issue #3720 exists.
3. I then fixed the issue with a simple modification in iOS/AirMaps/AIRMap.m
4. I tested with WMSTiles.js example on iOS simulator to verify that fix worked.
> Fix in WMSTile: typings & component removal on iOS

- docs/mapview.md
- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- lib/components/MapView.js
- lib/ios/AirMaps/AIRMapManager.m
Need to leverage use of iOS CLGeoCoder instead using paid third-party for conversion
No active issue, instead adding facility to get address.
I did create a working branch to integrate with RN project and verify. I'm using only simulator for testing.
> Use Default Geocoder to convert Coordinates by getting address

- docs/mapview.md
- index.d.ts
- lib/components/MapView.js
- lib/ios/AirMaps/AIRMap.h
- lib/ios/AirMaps/AIRMap.m
- lib/ios/AirMaps/AIRMapManager.m
NO
option to disable user location callout on iOS
manually on iOS device / simulator
> iOS add support for disabling userLocation callout

- README.md
- docs/marker.md
Nope
#3769 
No code just docs... But all of instructions were tested on a private project
> Better docs for custom markers

- lib/components/Geojson.js
I could not find any other PR to do the same thing. 
#3780 
- I tested this PR on both Android and iOS.
- Tested on both simulator and real devices
> feat:  Polyline tappable feature on GeoJson

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolyline.java
No
https://github.com/react-native-maps/react-native-maps/issues/3796
I don't have a good setup for testing this, so I have not done so.  I do think this will fix the issue, but I recommend that a more regular contributor test this prior to merging.
> Allow a previously dashed line to be made solid

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- lib/ios/AirMaps/AIRMapManager.m
No
#3850 and #3854
After testing the pre-release, I have found these two main issues listed above, which are solved with the above commit
> Fix crashes related to getAddressFromCoordinates for android and iOS

- package.json
No
#3812
Installed react-native-maps with npm7, without any additional flags.
> Allow React 17 peer dependency

- README.md
Unfortunately not.
**README.md** has a syntax error in **Overlaying other components on the map** section.
**Before:** Place components **_you that_** wish to overlay MapView underneath the MapView closing tag. Absolutely position these elements.
**After:** Place components **that you** wish to overlay MapView underneath the MapView closing tag. Absolutely position these elements.
English is my second language, but im pretty good at syntactics.
> Fixed the syntax of a sentence

- package-lock.json
- package.json
No
fixes #3922 
- updated `package-lock.json` and reinstalled packages
- executed `expo start` on CLI
- verified visually that the maps still loaded on iOS and Android
> fix: updated peer deps to maintain compatibility with expo init

- docs/installation.md
No
This PR fixed confusing red background color on ios installation. Red background makes us to remove that line.
Tested on my branch.
--
> docs(ios): remove unnecessary red background color

- example/android/build.gradle
- lib/android/build.gradle
No
Closes #3933
Built Android example app in both debug and release mode.
> [Android] Bump minSDKVersion to 21

- example/examples/EventListener.js
- lib/ios/AirMaps/AIRMapManager.m
No
Closes #3934
Added `onUserLocationChange` callback for iOS to the example app and confirmed heading output matches Google Maps
> [iOS] Add heading to onUserLocationChange

- README.md
This is merely an update to the README to help others who might similarly be hit with #3957.
No
#3957 
Reloaded README.md in GitHub and verified that formatting and content appear correctly.
> Updated README.md to address #3957 with XCode debugging tip

- package.json
No.
Fixes #3992
See description of #3992
> fix: allow wider version range for react-native-web peer dependency

- example/android/app/build.gradle
This was causing an "error type 3" when attempting to do `npm run android`
n/a
n/a
Android
Simply do `npm run android` after installing the required dependencies
> [android] Fix applicationId to com.example

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
No
#4074
Couldn't reproduce the issue mentioned, but the changes are quite harmless.
> fix(android): add null checks for map in MapView

- docs/overlay.md
> docs(overlay): fix table

- docs/heatmap.md
- docs/mapview.md
> Docs/address for coordinate & heatmap

- .github/workflows/pullRequest.yml
- CONTRIBUTING.md
> ci: add PR title linting

- .github/workflows/pullRequest.yml
> ci(pullRequest): add qoutes to lint pr title

- package.json
> build: don't allow warnings when linting

- package.json
> fix: remove upper react version limit

- example/ios/Podfile.lock
- example/ios/example.xcodeproj/project.pbxproj
- react-native-google-maps.podspec
Resolves #4157
No
#4157
Ran project on iOS with provider="google"
> feat(ios): bump google maps pods

- docs/mapview.md
> docs: add apple maps only note for showsPointsOfInterest

- CONTRIBUTING.md
No
None. Specifies to open PR's against beta.
> docs(contributing): update pr guideline

- android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
No
#4160
Ran an android project containing the changes.
> fix(android): remove use of lambda expression

- android/src/main/java/com/airbnb/android/react/maps/AirMapCalloutManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapOverlayManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapPolygonManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapPolylineManager.java
- android/src/main/java/com/airbnb/android/react/maps/ImageReader.java
No
None
Ran a project with the proposed changes on Android
> feat(android): migrate to androidx.annotation

- android/build.gradle
No
Opened the project in Android Studio successfully without errors.
> build(android): allow project to be opened as root

- docs/overlay.md
No
Fix #4236
Test `<Overlay>` component with correct bounds values.
> docs(overlay): fix bounds desc

- docs/polygon.md
Nop
None
I clicked on "Preview" in github
> docs(polygon): fix styling

- docs/mapview.md
> docs(mapview): add link to lite mode desc

- docs/mapview.md
> docs(mapView): add IOS note for onDoublePress

- ios/AirGoogleMaps/AIRGoogleMap.m
> feat(ios): initial region cleanup

- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- src/MapView.tsx
Part of the new arch preparation. Description in commits.
> feat: migrate calls to set native props

- src/MapView.types.ts
> fix(types): missing marker-press action for MapPressEvent

- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
> fix(android): animateToRegion not working with duration 0

- CHANGELOG.md
> docs(changelog): add missing releases to changelog.md

- src/MapView.tsx
> fix(android): onLayout not being called

- docs/mapview.md
> docs(MapView): add package visibility note to toolbarEnabled prop

- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- docs/installation.md
- package.json
- src/MapView.tsx
- yarn.lock
> fix(android): initial camera

- .github/ISSUE_TEMPLATE/bug_report.yml
> Add Expo SDK47

- ios/AirMaps/AIRMap.h
- ios/AirMaps/AIRMap.m
- ios/AirMaps/AIRMapManager.m
> fix(ios): followsUserLocation changes zoom level

- android/src/main/java/com/rnmaps/maps/MapView.java
> fix(android): crash when removing feature belonging to collection

- example/android/app/src/main/AndroidManifest.xml
I don't see a similar PR
have a typo in example project #4879
no test, just referencing Android Manifest.permission
https://developer.android.com/reference/android/Manifest.permission#ACCESS_COARSE_LOCATION
> fix(example): fix typo in AndroidManifest.xml for ACCESS_COARSE_LOCATION permission

- ios/AirGoogleMaps/AIRGoogleMap.m
- ios/AirMaps/AIRMapManager.m
No
https://github.com/react-native-maps/react-native-maps/issues/4908
logged the timestamp on the JS side with console.log, both on IOS and Android
> fix(AIRMap): fix location change timestamp

- android/build.gradle
update google play services
Staying up to date with google dependencies (maps and play services)
1. pre-commit passed
2. Physically on an android device
Some questions you might want to think about:
Affects google maps on android
> update android google maps dependencies

- src/MapView.tsx
No
Correctly the typo error
Just fix JS document not change the logic.
> Fix typo map type in document

- .github/workflows/pullRequest.yml
- example/babel.config.js
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/rnmshowcase.xcodeproj/project.pbxproj
- example/package.json
- example/src/examples/AnimatedMarkers.tsx
- example/src/examples/PanController.tsx
- example/yarn.lock
- src/MapMarker.tsx
- src/MapMarkerNativeComponent.ts
No, I haven't seen anyone trying to use reanimated in this library.
https://github.com/react-native-maps/react-native-maps/issues/4371
Physically on an iOS device
> fix(animation): Marker Animation using reanimated

- android/src/main/java/com/rnmaps/maps/MapManager.java
- android/src/main/java/com/rnmaps/maps/MapModule.java
- android/src/main/java/com/rnmaps/maps/MapView.java
- docs/installation.md
- example/react-native.config.js
- example/src/examples/GradientPolylines.tsx
- src/MapView.tsx
- src/index.ts
NO
- example now compiling again for android
- improve android map initialisation for Camera
- add support for choosing android renderer: LEGACY, LATEST
- hopefully will fix: #4997 #5014 
on an android device
> Android fixes

- README.md
- example/react-native.config.js
NO
Some code related to configuring react-native-maps to work with Fabric was removed from the previous releases.
physically on an android phone
> Example with fabric working

- android/build.gradle
- android/src/main/AndroidManifest.xml
No
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.rnmaps.maps" from the source AndroidManifest.xml: /builds/ReactNative/InitialCare/node_modules/react-native-maps/android/src/main/AndroidManifest.xml.
Building apk locally works. But in GitLab CI environment, the daemon build stops at this error
> Remove package as recommended by this error:

- example/ios/Podfile.lock
- example/ios/rnmshowcase/PrivacyInfo.xcprivacy
- example/package.json
- example/yarn.lock
- ios/PrivacyInfo.xcprivacy
No
[#5065](https://github.com/react-native-maps/react-native-maps/issues/5065)
Physically on an iPhone and pod install now works
> example working with react-native 0.74.1

- example/ios/rnmshowcase/PrivacyInfo.xcprivacy
- ios/PrivacyInfo.xcprivacy
No
https://github.com/react-native-maps/react-native-maps/issues/5007
feedback from Appstore review
> fix(iOS): iOS PrivacyInfo fix

- README.md
The word headache has no space.
No
None
none
none
> Fixing a small grammar mistake in README.md

- README.md
no
documentations
commit hook passed
> fix docs one more time

- src/MapPolyline.tsx
> Including export to PolylinePressEvent

- android/src/main/java/com/rnmaps/maps/MapManager.java
- android/src/main/java/com/rnmaps/maps/MapMarkerManager.java
No
https://github.com/react-native-maps/react-native-maps/issues/4989
when i add log to related code block its seems success
> add(Android): Added A11y for Map and Marker

- README.md
small change which caused confusion
No
just readme issue, there is not opened issue for this
No need to test on simulator
> fix: documentation on README.md

- example/src/App.tsx
- example/src/examples/GradientPolylines.tsx
- example/src/examples/GradientPolylinesFunctional.tsx
- ios/AirGoogleMaps/AIRGoogleMapPolyline.m
No, I am addressing a change that was implemented in this PR:
https://github.com/react-native-maps/react-native-maps/pull/4973
https://github.com/react-native-maps/react-native-maps/pull/4973 seems to have a negative side effect of allocating a lot of memory and never releasing it.
I am open to alternative approaches. I considered a dealloc override like is done here: https://github.com/react-native-maps/react-native-maps/blob/a169d3e019b3a8cb7ffb9caa9e4a37b5beda6ecd/ios/AirMaps/AIRMapMarker.m#L379-L381 but I'm not particularly up to date on obj-c best practices.
Let me know your preference and I'd be glad to work on it.
I have updated the GradientPolylines example to reflect the scenario. I also created a GradientPolylinesFunctional example if you are opposed to updating the existing …
> Fix(ios): fix polyline memory leak on coordinate update

- docs/installation.md
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/rnmshowcase.xcodeproj/project.pbxproj
- ios/AirGoogleMaps/AIRGoogleMap.m
- ios/AirGoogleMaps/AIRGoogleMapManager.m
- react-native-google-maps.podspec
No
Add support to MapID and other new google map features
Physically on an iPhone
> update GoogleMaps SDK to 8.4.0 and Google-Map-Utils to v5.0.0

- android/src/main/java/com/rnmaps/maps/MapManager.java
- android/src/main/java/com/rnmaps/maps/MapView.java
- example/src/examples/DefaultMarkers.tsx
- src/MapView.tsx
No
Partially #4472 
Physically on an android device
> feat(android): add support for disabling PoIClick

- .github/ISSUE_TEMPLATE/bug_report.yml
> Add new Expo SDK versions in bug_report.yml

- ios/AirGoogleMaps/AIRGoogleMapCircle.m
- ios/AirGoogleMaps/AIRGoogleMapPolygon.m
- ios/AirGoogleMaps/AIRGoogleMapPolyline.m
This PR fix the ios google maps marker color update:
https://snack.expo.dev/4kryDTGdDqr1zkOgnYq-g
> fix(ios): color update in AIRGoogleMap

- .github/workflows/push.yml
NO
release away from master 
let's find out
> chore(CI): introduce alpha branch

- README.md
No
First release of Alpha package
N/A
> feat(Fabric): testing new commit

- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/rnmshowcase.xcodeproj/project.pbxproj
- example/ios/rnmshowcase/AppDelegate.mm
- react-native-google-maps.podspec
No
https://github.com/react-native-maps/react-native-maps/issues/5206#issuecomment-2552443873
Physically, example app with with google maps enabled on an iphone
> fix(ios): re-enable google-maps for iOS

- android/build.gradle
- package.json
No
Android build issue reported here: 
https://github.com/react-native-maps/react-native-maps/issues/5206#issuecomment-2559374025
locally android build is passing
> fix(android): android build with Fabric enabled

- README.md
> feat: fabric support

- react-native-maps-generated.podspec
> fix: simplified generated podspec to pass lint

- react-native-maps-generated.podspec
No
Broken generated podspec file
CI should pass
> fix: revert to working generated podspec

- .github/workflows/push.yml
fix push.yml after moving to monorepo
linter passes
> feat: update push.yml

- example/tsconfig.json
No
https://github.com/react-native-maps/react-native-maps/issues/5397
npx tsc --noEmit
works in both top level and example
> fix: remove unnecessary tsconfig.json from

- android/src/main/java/com/rnmaps/maps/MapView.java
No
https://github.com/react-native-maps/react-native-maps/issues/5469
https://github.com/react-native-maps/react-native-maps/issues/5429
Yes, android
> fix(android): onRegionChange not being dispatched

- package.json
- plugin/src/ios.ts
No
[#5481](https://github.com/react-native-maps/react-native-maps/issues/5481)
n/a
> fix(expo): update plugin to use new podspec

- src/AnimatedRegion.ts
- src/MapView.tsx
- tsconfig.json
No
https://github.com/react-native-maps/react-native-maps/issues/5479
no more ts issues reported
> fix(ts): more fixes for ts issues

- docs/installation.md
Saw issues where people were confused about the expo plugin and why it wasnt working for them. Updated the installation docs based on the original PR and the answers in the issues
No
[Expo documentation is not correct](https://github.com/react-native-maps/react-native-maps/issues/5477)
I checked that the markdown looked ok in the github preview
> fix: Added expo plugin version information

- ios/AirMaps/RNMapsMapView.mm
No
https://github.com/react-native-maps/react-native-maps/issues/5451
example app (iOS)
> fix(iOS): appleMap module calls

- example/package.json
- example/yarn.lock
No
react-native android codegen Image prop wasn't working
Android emulator, example app wasn't showing Marker icons now it does
> chore(example): update react-native to 0.79.3

- android/src/main/java/com/rnmaps/fabric/MarkerManager.java
- android/src/main/java/com/rnmaps/maps/MapMarker.java
No
https://github.com/react-native-maps/react-native-maps/issues/5402
Android emulator
> fix(android): marker was constantly re-rendering

- ios/AirMaps/AIRMapMarker.m
- ios/AirMaps/RNMapsMarkerView.mm
- ios/generated/RNMapsSpecs/ComponentDescriptors.cpp
- ios/generated/RNMapsSpecs/ComponentDescriptors.h
- ios/generated/RNMapsSpecs/EventEmitters.cpp
- ios/generated/RNMapsSpecs/EventEmitters.h
- ios/generated/RNMapsSpecs/Props.cpp
- ios/generated/RNMapsSpecs/Props.h
- ios/generated/RNMapsSpecs/ShadowNodes.cpp
- ios/generated/RNMapsSpecs/ShadowNodes.h
- ios/generated/RNMapsSpecs/States.h
- src/specs/NativeComponentMarker.ts
No
https://github.com/react-native-maps/react-native-maps/issues/5495
iOS simulator
> feat(AppleMaps): add support for centerOffset for Marker

- ios/AirGoogleMaps/RNMapsGooglePolygonView.mm
- ios/generated/RNMapsSpecs/Props.cpp
- ios/generated/RNMapsSpecs/Props.h
- src/specs/NativeComponentCircle.ts
- src/specs/NativeComponentGooglePolygon.ts
- src/specs/NativeComponentPolyline.ts
No
https://github.com/react-native-maps/react-native-maps/issues/5523
example app iOS simulator
> fix(AppleMaps): polygon strokeWidth

- src/MapOverlay.tsx
> chore(docs): update Overlays bounds doc

- android/src/main/java/com/rnmaps/maps/MapView.java
No
#5645
tested on android emulator
> fix(android): onRegionChangeComplete on initial map loaded

- src/createFabricMap.tsx
- src/specs/NativeComponentGoogleMapView.ts
- src/specs/NativeComponentMapView.ts
`"Attempt to read from field 'com.google.android.gms.maps.GoogleMap com.rnmaps.maps.MapView.map' on a null object reference"`
Tested on android emulator using the example app.
How to reproduce:
Check master branch, open the example, go to CamerControl and use a button.
fix: #5620 and assign correct types
@Doug821 please review
> fix: fixed nullpointer due null react view tag

- android/src/main/java/com/rnmaps/fabric/MarkerManager.java
- android/src/main/java/com/rnmaps/maps/MapMarker.java
- src/MapMarker.tsx
- src/MapMarkerNativeComponent.ts
No
https://github.com/react-native-maps/react-native-maps/issues/5593
Tested on Android emulator by calling `redraw` method with `tracksViewChanges` disabled.
Tested using Browserstack and real devices by calling `redraw` method with `tracksViewChanges` disabled.
> [Android] Restore `redraw` method

- android/src/main/java/com/rnmaps/fabric/MarkerManager.java
- android/src/main/java/com/rnmaps/maps/MapView.java
Reverts react-native-maps/react-native-maps#5660
> Revert "Bug/react 19 parallel features"

- android/src/main/java/com/rnmaps/fabric/MarkerManager.java
- android/src/main/java/com/rnmaps/maps/MapView.java
No
https://github.com/react-native-maps/react-native-maps/issues/5497
How did you test this PR?
Android emulator, the bug was reproducible here:
https://github.com/ammar-madni/repro-index-out-of-bounds/
> fix: crash android react 19 parallel features

- android/src/main/java/com/rnmaps/maps/MapView.java
No
https://github.com/react-native-maps/react-native-maps/issues/5595
and other similar issues reported
Android emulator
> feat(android): support saving view state

- example/ios/Podfile.lock
- example/ios/rnmshowcase.xcodeproj/xcshareddata/xcschemes/rnmshowcase.xcscheme
- example/ios/rnmshowcase/Info.plist
No
example wasn't working on iOS
ios emulator
> fix(example): example wasn't starting

- android/src/main/java/com/rnmaps/maps/MapView.java
- ios/AirMaps/RNMapsMapView.mm
No
https://github.com/react-native-maps/react-native-maps/issues/5741
android and iOS
> fix: set camera

- android/src/main/java/com/rnmaps/fabric/MarkerManager.java
- android/src/main/java/com/rnmaps/maps/MapMarker.java
No
https://github.com/react-native-maps/react-native-maps/issues/5736
Didn't test it, but looks clear
> fix(android): fix remove marker from map issues

- android/src/main/java/com/rnmaps/fabric/MapViewManager.java
- android/src/main/java/com/rnmaps/maps/MapView.java
https://github.com/react-native-maps/react-native-maps/pull/5666
https://github.com/react-native-maps/react-native-maps/issues/5722
couldn't test, no reproducible example
> fix(android): attempt to fix lifecycle issues on more time
