react-native-maps/react-native-maps

- ios/AirMaps/AIRMapManager.m
It crashes because it receives a `MKUserLocation`.
```
2016-01-21 16:35:57.544 App[34016:4472995] -[MKUserLocation setMap:]: unrecognized selector sent to instance 0x7f8b83a2c5f0
2016-01-21 16:35:57.561 App[34016:4472995] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MKUserLocation setMap:]: unrecognized selector sent to instance 0x7f8b83a2c5f0'
*** First throw call stack:
(
0   CoreFoundation                      0x000000010a94df45 __exceptionPreprocess + 165
1   libobjc.A.dylib                     0x00000001070b3deb objc_exception_throw + 48
2   CoreFoundation                      0x000000010a95656d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3   CoreFoundation                      0x000000010a8a3eea ___forwarding___ + 970
4 …
```
> Fix user location display

- android/src/main/java/com/AirMaps/AirMapView.java
I had an issue because I didn't set properly Google Service and the map was not rendering. So when leaving the app it just crashed because the map was not instantiated yet.
Not sure if thats the best way to handle it though.
> Fix when map is not loaded and app goes to background

- components/MapView.js
Fixes #28 
In order to use the non-deprecated `getMapAsync` API on android, we had to add some code to set the region when the `onLayout` event gets fired.  Apparently Android 5.0 seems to call this event a LOT, where as other android versions don't, which was causing some jankiness. This code ensures that the region is only set on the first onLayout call.
> Only setRegion on layout once

- ios/AirMaps/AIRMapManager.m
`duration` was being passed, but wasn't being used when calling `setRegion:`.
> Use duration when animating setRegion:

- android/src/main/java/com/AirMaps/AirMapMarker.java
#77 
set marker as null once it's removed from the map
Not yet sure if there are situations where a marker is removed from and then re-added to the map.
> Potential fix for #77

- android/src/main/java/com/AirMaps/AirMapView.java
- android/src/main/java/com/AirMaps/RegionChangeEvent.java
if the user tilts the camera the center of the viewed region is far off in the
distance, which would cause any actions based on onRegionChange lat/lng values
to appear off center
this also fixes lat/lng values being too far north/south if the user is very
zoomed out due to mercator distoritions
> android: use camera target instead of region center for onRegionUpdate lat/lng

- ios/AirMaps/AIRMap.m
This fixes a crash when iOS 7 and 8 mapview properties `showsCompass`, `showsScale` or `showsTraffic` are defined. These properties are only available on iOS 9+.
Similar to the origin react-native MapView (RCTMap.m) this checks if the super class (MKMapView) has selectors to set and get these parameters. If not it does nothing or return false.
> Fix crash on iOS 7 and 8 with iOS 9+ API calls

- package.json
See https://github.com/oblador/react-native-vector-icons/issues/76#issuecomment-165959265
Unable to install with RCs.
> Remove peerDepencies

- android/build.gradle
- docs/installation.md
**Problem:** Cannot be used out of the box with [`react-native-gcm-android`](https://github.com/oney/react-native-gcm-android) since that required play-services `8.3.0`. Resulting name collision results in cryptic runtime errors. For comparison, [`react-native-gcm-android` installation instructions](https://github.com/oney/react-native-gcm-android#installation) include:
```
compile 'com.google.android.gms:play-services-gcm:8.3.0' // <- Add this line
```
**Solution:** Feel free to accept or reject this PR, but the convention of moving dependencies to the app makes a certain amount of sense to me so that the repo doesn't need to be forked in order to fix the issue. This approach requires negligible extra work, has the same result, and makes the dependency explicit and somewhat easier to …
> Remove hard-coded play-services API version in deps

- docs/installation.md
- react-native-maps.podspec
I use cocoapods for some other dependencies (not react-native related) and rnpm never plays nice with it. The podspec file is all that's needed for someone to install via cocoapods.
You don't have to publish this to cocoapods (although you can if you want), but you do have to keep the version updated within the podspec file going forward.
I hope you'll accept this to make some of our lives easier. Thanks for the awesome package!
> Cocoapods spec + installation instructions

- ios/AirMaps/AIRMap.m
Fixes #54 
The Circle wasn't updating position, when center or radius props changed. There was a missing line in `AIRMap.m`.
> Fix Circle overlay

- components/MapMarker.js
- docs/mapview.md
- docs/marker.md
`onSelect` and `onDeselect` are only available for iOS at the moment.
Added `@platform ios` for `onDeselect ` in `MapMarker.js` but it was already there for `onSelect`
> Marker select deselect doc update

- README.md
- components/MapView.js
- example/App.js
- example/examples/TakeSnapshot.js
- ios/AirMaps/AIRMapManager.m
Added functionality to take snapshot of map with annotation views for ios. You can configure image size and center point. I have tested it both in simulator and real device (iPhone SE). I also work on android implementation as i need to use it in both platforms for app I am building. So I will soon send pull request with android version as well (If this one is accepted :-)). PR contains example and readme update.
> Taking snapshots of map for ios

- android/lib/build.gradle
Right now it seems that android is locked to 0.25.1.
I know we made the change recently after react-native-maps has been put on maven, just wondering if it is necessary to lock the version going forward or using  'com.facebook.react:react-native:+' is fine.
> Allow other versions of react-native than 0.25.1

- android/src/main/java/com/AirMaps/AirMapManager.java
- android/src/main/java/com/AirMaps/AirMapView.java
- android/src/main/java/com/AirMaps/AirPackage.java
- docs/installation.md
- example/android/app/src/main/java/com/airmapsexplorer/MainActivity.java
Fix for#165 and #271 - Android 6.0 crashing on devices such as Xperia Z5 Compact, Z5 Bond and others. 
It passes the activity to the package, manager and view so that it can be used in place of the app context when initialising the MapView component.
The new code as also been tested on the following devices to ensure it continues to work as before:
Nexus 4 (Android 5), Nexus 5 (Android 6), Nexus 6P (Android 6)
It requires a change to an app's MainActivity.java to pass `this` when creating the AirPackage: `new AirPackage(this)` rather than `new AirPackage()` in the current version.
> 0.4 stable

- ios/AirMaps/AIRMapMarker.m
When using a custom image for the marker, and when the ```imageLoader``` sets the image before the ```reactSetFrame``` method is called on the marker, the size of the view is incorrectly set, resulting in an invisible marker.
This commit makes sure that, when an image is set before the ```reactSetFrame```, we transfer the size of the image to the marker.
> iOS: Fix a marker not being shown when using a custom image

- ios/AirMaps/AIRMapMarkerManager.m
According to the docs `onPress` should return coordinates of the maker, similiar to `onSelect`. This was working fine for Android but was missing from iOS.
/cc @jrichardlai
> [MapMarker] Return id and coordinates on marker press

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- components/MapView.js
- docs/mapview.md
- example/App.js
- example/examples/CachedMap.js
- example/examples/LoadingMap.js
- ios/AirMaps/AIRMap.h
- ios/AirMaps/AIRMap.m
- ios/AirMaps/AIRMapManager.m
Added ability for caching map as static image for performance reason, also added loading indicator to be display while map is being cache.
New props; `cachedEnabled`, `loadingEnabled`, `loadingBackgroundColor`, `loadingIndicatorColor`
Big thanks to @jrichardlai for his contribution and guiding me on this commit.
Superseed #91
> Added ability for caching map as static image

- react-native-maps.podspec
This allows for support for ReactNative versions >= 0.25.
> Remove React dependency from podspec

- android/gradle.properties
- android/lib/build.gradle
- example/android/app/build.gradle
- example/examples/AnimatedMarkers.js
- example/examples/AnimatedPriceMarker.js
- example/examples/AnimatedViews.js
- example/examples/CachedMap.js
- example/examples/Callouts.js
- example/examples/CustomCallout.js
- example/examples/DefaultMarkers.js
- example/examples/DisplayLatLng.js
- example/examples/DraggableMarkers.js
- example/examples/EventListener.js
- example/examples/LoadingMap.js
- example/examples/MarkerTypes.js
- example/examples/Overlays.js
- example/examples/PanController.js
- example/examples/PolygonCreator.js
- example/examples/PolylineCreator.js
- example/examples/PriceMarker.js
- example/examples/TakeSnapshot.js
- example/examples/ViewsAsMarkers.js
- example/examples/finalindexfile.js
- example/package.json
- package.json
This updates the android lib and sample to make it work with RN 0.27.2.
Unfortunately Maven Central won't let us upload the artifact with an
open dependency on RN (`+` version), so I locked it to 0.27.2 and above.
Also had to update some outdated js imports with the new ones.
Please review @lelandrichardson @christopherdro
> Bump Android version to 0.6.0 and use RN 0.27.2

- ios/AirMaps/AIRMapMarker.m
There is a warning after upgrading React Native to 0.28.0 about `loadImageWithTag` being deprecated. I saw it when loading a custom image for a marker. I updated the function to what I think is the new way of loading these images. 
I'm not sure if `clipped` should be `YES` by default but I think that's the case now.
Hope this helps :)
> Fix warning for iOS "loadImageWithTag is deprecated" for RN 0.28.0

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapView.java
For some reason this was not triggered before but sometimes `this.loadingIndicatorColor` is null then calling `this.setLoadingIndicatorColor` will trigger a null pointer exception
> [FIXBUG] Not calling setLoadingIndicatorColor when null

- ios/AirMaps/AIRMapMarker.m
Reverting this for now as it breaks build https://github.com/lelandrichardson/react-native-maps/pull/333
> Revert "Fix warning for iOS "loadImageWithTag is deprecated" for RN 0.28.0

- android/gradle.properties
- android/lib/gradle.properties
- docs/installation.md
- example/android/gradle.properties
* And basic gradle.properties reorg to allow that
Previous `installation.md` was configuring android projects to pull their `react-native-maps` artifact from maven, and not `node_modules`. It was also uselessly [adding a settings.gradle](https://github.com/lelandrichardson/react-native-maps/blob/master/docs/installation.md#android) project for `:react-native-maps` which was never used.
This change fixes those instructions, and related project structure, to allow us to build android projects with `react-native-maps` coming from `node_modules`, just as ios projects are built.
I'm not informed about our reasoning for publishing to maven at all, but I don't believe this PR breaks that functionality.
> [android] installation instructions to actually use node_modules

- android/lib/build.gradle
- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- android/lib/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
- docs/installation.md
React native 0.29 has some changes to the way they initialize libraries, which means they are initialized from the `Application` rather than the `MainActivity`. We added the Activity as a constructor argument to `MapsPackage` in [PR#276](https://github.com/lelandrichardson/react-native-maps/pull/276) to fix Sony Xperia devices with Android 6.0 crashing #271.
After some experimentation and testing we've found that if you supply `ReactContext.getBaseContext()` to the Google Maps API you can get away with not needing the MainActivity. I have also left the `public MapsPackage(Activity activity) { }` constructor for backwards compatibility, but if you'd rather this was removed, let me know and I'll update the PR.
I've also updated the `build.gradle` file as per #359 to get the lib building …
> RN0.29 compatability

- ios/AirMaps/AIRMapMarker.m
Update shouldUsePinView to handle when `subviews` are not yet updated to reflect `reactSubviews`.
Feel free to abandon this but quick attempt at a fix of an issue where markers were using the default pins instead of the custom react subviews. Stepping through the code it looks like this runs before [`UIView.didUpdateReactSubviews`](https://github.com/facebook/react-native/blob/master/React/Views/UIView+React.m#L132) when `subviews` are actually updated.
> Fix shouldUsePinView

- ios/AirMaps/AIRMap.h
- ios/AirMaps/AIRMapCallout.h
- react-native-maps.podspec
Ok, so my last PR removed the React dependency as it's latest pod source references an outdated version of `0.14`.  In order to get this completely working I am doing the following in my project's `ios/Podfile`:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
workspace 'my-project.xcworkspace'
project 'my-project.xcodeproj'
target 'my-project' do
pod 'React', :path => '../node_modules/react-native'
pod 'React/Core', path: '../node_modules/react-native'
pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
pod 'React/RCTImage', :path => '../node_modules/react-native'
pod 'React/RCTNetwork', :path => '../node_modules/react-native'
pod 'React/RCTText', :path => '../node_modules/react-native'
pod 'React/RCTWebSocket', :path => …
```
> Getting to work on iOS with 0.27

- ios/AirMaps/AIRMapMarker.m
[`loadImageWithTag`](https://github.com/facebook/react-native/blob/ba4c34c0db004cda9fb561b3bdf5224d518ab32d/Libraries/Image/RCTImageLoader.m#L755) is deprecated and shows warnings on RN 0.29.
On iOS, render a map with a marker that has image prop set. See marker is rendered correctly and no deprecation warnings.
```
<MapView ...>
<MapView.Marker ... image={require('./pin.png')} />
</MapView>
```
> Update AirMapMarker to use loadImageWithURLRequest

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- components/MapView.js
This button is enabled by default when showsUserLocation is true; it's the gray button that shows on the top right and centers on the user location on press.
This is useful if you want to implement a different version of that in React Native, for instance.
> Take prop to hide the "my location" button in Android

- ios/AirMaps/AIRMapManager.m
In my opinion this should be the developers choice, without this prop it is unnecessary hard to develop a mapkit-like behaviour for ios where the map follows the users location.
<Button 
icon={like.the.arrow.on.ios.maps}
placement={top.left.or.anywhere.really.on.the.map}
onPress={this.setState(followuser: toggle true/false} />
<Map followuser={this.state.followuser}>
For Android you'll still need a custom camera controller, but that should be the developers choice how to handle this situation. The followuser is very smooth for iOS.!
> Follow user location continuously, if specified

- components/MapView.js
We encountered an issue at a hackathon where props (and therefore styles) was not being passed through: this means that if the map isn't ready (`this.state.isReady` is false), it is invisible unless it was given a width and height by its parent. This is an issue because on genymotion, where maps aren't available, isReady never becomes true and we can never see the error message.
> Pass through style even when map isn't ready

- android/lib/build.gradle
- ios/AirMaps/AIRMap.h
- ios/AirMaps/AIRMapCallout.h
- package.json
Here's a few things that will make `react-native-maps` work again now that React Native 0.30 is here.
Before you read to code, i just want ensure I'm not trolling you here. I adore `react-native-maps` and just want it to work out of the box and survive upgrades of React Native.
* Set the dependency to for React Native to `+`.    I know y'all have issues with this, but I believe this is straight forward and works.  <3
* Downgrade play services back to 8.4.0 as this will cause android clients to need to upgrade to work.  Just a compatibility thing.
* Two small header imports were broken.
* Set the `rnpm` hint in `package.json` to point it to the right code so it gets linked properly.
* Changed the dependency to peerDependency.  Just relies on the host to install the right version.  This …
> Supports React Native 0.30 on both platforms again

- docs/installation.md
Users may mistakenly modify android/build.gradle instead of android/app/build.gradle. This PR clarifies which file to modify.
> Clarify which build.gradle to modify in Installation.md

- docs/installation.md
Adding `MapsPackage` to the list doesn't work if the import statement hasn't been added to the file.
> Include import line in Java application

- components/MapCallout.js
- components/MapCircle.js
- components/MapMarker.js
- components/MapPolygon.js
- components/MapPolyline.js
- components/MapView.js
Remove the unused `NativeMethodsMixin`, which is undefined in
`react-native` 0.32.0, causing yellowbox warnings.
Related: #490
cc: @lelandrichardson
> Remove unused `NativeMethodsMixin` for compat with RN 0.32

- ios/AirMaps/AIRMapManager.m
The current implementation will crash if you call fitToSuppliedMarkers while showsUserLocation is set to true because of an unchecked cast of the MKUserLocation marker.
> [CRASH] Added check on marker class in predicate

- android/lib/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
Update AirMapManager to use Activity obtained from ReactContextBaseJavaModule (part of update from [RN v0.29.0](https://github.com/facebook/react-native/releases/tag/v0.29.0))
This might address issues like #165 
Note: Not tested for backward compatibility
> Use Activity to initialize Google Map

- example/App.js
The example app had bad UX because you could only scroll in the middle
of the screen. Make the `<ScrollView />` use `StyleSheet.absoluteFill`
to make it full-width.
> Make ScrollView in example/App.js full-width

- android/build.gradle
In #502, the local maven url pointing to the `react-native` node module
changed to work better for the example app. However, that broke the path
to `react-native` when developing in the context of the library, not the
example app. In this PR, specify both paths.
cc: @felipecsl @chrisknepper
> Fix path to react-native when developing outside of the example app

- android/build.gradle
Bumping build.gradle to use latest version of google-play, should fix crashing when conflicting with other node modules that use the 9.+ version
> Bumped google-play-things in build.gradle to 9.+

- android/gradle.properties
- react-native-maps.podspec
Update the respective Android & iOS versioning files to indicate we're
on version 0.8.0 instead of 0.7.1.
Does this warrant publishing 0.8.1 (with the proper files updated 😜) so that people can consume the correct versions with Cocoapods/Gradle?
to: @christopherdro @lelandrichardson
> Fix a few spots where forgot to update version from 0.7.1 to 0.8.0

- android/build.gradle
Currently it's not possible to build an Android app when using RN 0.32.1 because it's looking for version 0.32.0, this commit fixes this issue.
> Use latest version of RN to build Android

- CHANGELOG.md
- android/gradle.properties
- package.json
- react-native-maps.podspec
We realized immediately after publishing 0.8.1 that the NPM package contained some test code in the example2/ directory that contained a copy of the react-native package, causing this packager error:
```
Failed to build DependencyGraph: @providesModule naming collision:
Duplicate module name: String.prototype.es6
Paths: /Users/<path to project>/node_modules/react-native-maps/example2/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js collides with /Users/<path to project>/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js
This error is caused by a @providesModule declaration with the same name accross two different files.
```
0.8.2 is identical to 0.8.1, except with the offending code removed from …
> Version 0.8.2

- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/java/com/airbnb/android/react/maps/AirMapCalloutManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
* Remove unused variables and fields
* Fix compiler warnings (unchecked, deprecation, etc)
> [Android] Minor code cleanup

- ios/AirMaps/AIRMapMarker.h
- ios/AirMaps/AIRMapMarker.m
This helps when vendoring the library elsewhere, since you can search for symbols beginning with AIR- and SM-.
> Add class prefix to EmptyCalloutBackgroundView

- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
This commit prevents the crash mentioned in #180. It is identical to the implementation in `AirMapView#fitToSuppliedMarkers()`.
This doesn't actually fix the issue mentioned in #180 because while the app no longer crashes, the elements aren't zoomed unless you use a setTimeout hack or something similar. @igrayson has written about this there.
It would be great to figure out why that isn't working, however.
> Don't fit to elements if no positions added

- README.md
- android/src/main/java/com/airbnb/android/react/maps/AirMapLiteManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
- components/MapView.js
- docs/mapview.md
- example/App.js
- example/examples/LiteMapView.js
Following discussion https://github.com/lelandrichardson/react-native-maps/issues/300
> Support Android LiteMode

- example/App.js
In #548, we added Google Maps support for iOS. We changed the example
app to list examples based on whether they support Google Maps on iOS.
The logic was such that on Android it only showed the examples that are
iOS + Google Map compatible, however on Android this condition is
irrelevant, this commit changes it to show all examples on Android,
regardless.
to: @gilbox
> Fix list of examples on Android

- README.md
- components/AnimatedRegion.js
- components/MapView.js
This pull request replaces the old one (#592) (was having too much trouble rebasing due to upstream changes). This pull request is rebased on the latest master and adds an additional check to verify that the AnimatedWithChildren class has been correctly obtained.
> Added support for AnimatedRegion without modifying the AnimatedImplementation.js of react-native

- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
Remove unused variable `tileMap`.
It was left over from a rebase from #595.
cc: @cascadian
> Remove unused tileMap variable from AirMapView

- example/examples/DefaultMarkers.js
- ios/AirGoogleMaps/AIRGoogleMap.m
Once created, markers were never going away. This PR fixes that. It also adds the ability to test this functionality in "Default Markers" demo.
@spikebrehm @lelandrichardson 
@felipecsl
> [google][ios] fix markers never going away for provider="google"

- example/App.js
- example/examples/CustomMarkers.js
- example/ios/AirMapsExplorer.xcodeproj/project.pbxproj
- example/ios/AirMapsExplorer.xcodeproj/xcshareddata/xcschemes/AirMapsExplorer.xcscheme
- example/ios/Podfile.lock
- ios/AirGoogleMaps/AIRGoogleMapMarker.m
- ios/AirGoogleMaps/DummyView.h
- ios/AirGoogleMaps/DummyView.m
- DummyView is used to create virtual tree
- Add CustomMarkers example
- Prevent annoying errors from showing up with OS_ACTIVITY_MODE disable, see here https://github.com/facebook/react-native/issues/9921#issuecomment-250078139
Adding children to markers is still buggy, but this PR at least improves the situation when adding an `image` prop to the marker.
@spikebrehm @lelandrichardson
> [google] refactor AIRGoogleMapMarker to use DummyView

- components/decorateMapComponent.js
stuff like `map.fitToElements()` was broken b/c of this.
> [android] fix getAirMapName to fix ref-based commands

- android/build.gradle
- example/android/build.gradle
fix the directories. 
@spikebrehm @lelandrichardson @felipecsl
> [android] fix gradle build setup for explorer, bump to gradle 2.2.0

- ios/AirMaps/AIRMapMarker.m
- package.json
added fix to RCTImageLoader, missing `partialLoadBlock:nil`
see https://github.com/airbnb/react-native-maps/blob/master/ios/AirMaps/AIRMapMarker.m#L217
```Objective-C
_reloadImageCancellationBlock = [_bridge.imageLoader loadImageWithURLRequest:[RCTConvert NSURLRequest:_imageSrc]
size:self.bounds.size
scale:RCTScreenScale()
clipped:YES
resizeMode:RCTResizeModeCenter
progressBlock:nil
partialLoadBlock:nil
completionBlock:^(NSError *error, UIImage *image) {
if (error) {
// TODO(lmr): do something with the error?
NSLog(@"%@", error);
}
dispatch_async(dispatch_get_main_queue(), ^{
self.image = image;
});
}];
```
> Upgraded to RN 0.35

- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- components/MapView.js
On iOS (Apple Maps) clicking a marker doesn't move the map but on Android clicking a marker causes the map to move.  This PR adds a property that lets that behavior be disabled.
Test plan (on Android):
* Verify the callout still appears when clicking a pin
* Verify the map moves if the property isn't specified
* Verify the map doesn't move if the property is set to false.
Before:
After:
> [android] Add parameter to disable the moving on marker press

- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- example/android/build.gradle
There is no need for us to manually call onPause/onResume in AirMapView.
please review @lelandrichardson @spikebrehm @gilbox 
Fixes #414
> Fixes crash during Activity onPause()

- example/ios/Podfile.lock
- example/package.json
- ios/AirGoogleMaps/AIRGoogleMapMarker.m
- package.json
Update the example app for RN 0.35.0.
Also fix the same bug that #680 fixes but for `AIRGoogleMapMarker`.
Also update the React dependency to 15.3.1, which is required for RN => 0.34.
to: @lelandrichardson @gilbox @felipecsl
> Update example app for RN 0.35, fix Gmaps bug for 0.35

- ios/AirGoogleMaps/AIRGoogleMapMarker.m
Prevent triggering irrelevant imageLoader call, thus avoiding an exception.
> Fix dynamic imageSrc removal

- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
This allows the containing scrollview to perform a scrollview scroll by dragging on the map. (Previously, the map would absorb the touches, and then not scroll the map _or_ the scrollview, which was bad.)
> If we've disabled scrolling within the map, then don't capture the touch events

- android/build.gradle
Switch to use the latest Google Play Services.  
The pain point is that by specifying a specific version it doesn't work with other libraries which specify the latest version of Google Play Services (which most do).  It causes a crash because when it is compiled it will include some of the latest version and some of 9.4.0 and then when it runs it crashes.
It's generally safe to assume users have the latest Google Play Services as the updates are pushed automatically.  As Google says "Google Play services gives you the freedom to use the newest APIs for popular Google services without worrying about device support. Updates to Google Play services are distributed automatically by the Google Play Store and new versions of the client library are delivered through the Android SDK Manager." …
> Use latest Google Play Services

- components/decorateMapComponent.js
Fixes https://github.com/airbnb/react-native-maps/issues/683 caused by https://github.com/airbnb/react-native-maps/pull/548.
In #548, MapMarker.js was changed from 
`const AIRMapMarker = requireNativeComponent('AIRMapMarker', MapMarker);` to 
`const AIRMapMarker = this.getAirComponent();`.  
`AirMapMarker` is what is returned in the render method.
The bug was that `this.getAirComponent()` was returning a new native component each time causing a re-render.  This only happened for the default component, not the other ones since they were cached.  The fix is to cache the default component.
Note: this seems to affect map markers with arbitrary views inside them the most.  
Before:
After:
> [marker flicker]  Fix flicker of map pins on state change

- android/src/main/java/com/airbnb/android/react/maps/AirMapPolygon.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapPolygonManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapPolyline.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapPolylineManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- ios/AirMaps/AIRMapManager.m
- ios/AirMaps/AIRMapPolygon.h
- ios/AirMaps/AIRMapPolygonManager.m
- ios/AirMaps/AIRMapPolyline.h
- ios/AirMaps/AIRMapPolylineManager.m
Adds onPress handlers for polygons and polylines.
- On Android, uses the native `setOnPolygonClickListener` and `setOnPolylineClickListener`
- On iOS, loops overlays in `handleMapTap` and finds if the tap is inside a polygon, or if the closest polyline is within 10 pixels of the tap.
> Add onPress for polygons and polylines on iOS and Android

- components/MapUrlTile.js
- example/App.js
- example/examples/CustomTiles.js
- example/ios/AirMapsExplorer.xcodeproj/project.pbxproj
- ios/AirGoogleMaps/AIRGoogleMap.h
- ios/AirGoogleMaps/AIRGoogleMap.m
- ios/AirGoogleMaps/AIRGoogleMapURLTileManager.m
- ios/AirGoogleMaps/AIRGoogleMapUrlTile.h
- ios/AirGoogleMaps/AIRGoogleMapUrlTile.m
- ios/AirGoogleMaps/AIRGoogleMapUrlTileManager.h
* Added support for custom tiles with googles maps on iOS
* Updated current example
> [iOS] Google Maps Custom Tile Support

- docs/polygon.md
- docs/polyline.md
- example/examples/EventListener.js
- Adds a polygon and polyline with `onPress` handlers to the "Events" example
- Fixes an issue where recording of map events was overriding recording of marker/overlay events. `setState` in `recordEvent` now takes a function with previous state to ensure an atomic update occurs.
- Adds docs for polygon + polyline onPress event
> [iOS][Android] Add example and docs for polygon+polyline onPress events

- docs/mapview.md
Updated the documentation to provide a better clarification on when `onRegionChange` fires, as it seems like it's exclusive to user input.
#827
> Clarified documentation for `onRegionChange`

- components/MapPolygon.js
- example/examples/PolygonCreator.js
- ios/AirGoogleMaps/AIRGoogleMapPolygon.h
- ios/AirGoogleMaps/AIRGoogleMapPolygon.m
- ios/AirGoogleMaps/AIRGoogleMapPolygonManager.m
- ios/AirMaps/AIRMapPolygon.h
- ios/AirMaps/AIRMapPolygon.m
- ios/AirMaps/AIRMapPolygonManager.m
- ios/AirMaps/RCTConvert+MoreMapKit.m
Here is my attempt at implementing polygon holes for Apple Maps and Google Maps on iOS. See an attached screenshot showing isochrons on Apple Maps.
I have not programmed in Objective C before, so there may be issues with the code. Feel free to let me know.
> Add support for polygon holes for Apple Maps and Google Maps on iOS

- example/App.js
- example/examples/LegalLabel.js
- ios/AirMaps/AIRMap.m
Fixes #470. This will add support for `legalLabelInsets` prop on iOS with Apple Maps. Code is adapted from RN core.
> Fixes #470. Support legalLabelInsets on Apple Maps

- docs/mapview.md
- example/examples/LegalLabel.js
- ios/AirMaps/AIRMap.m
Added docs for legalLabelInsets as well. Related to #840 
While property is structurally identical to EdgePadding, used for region fitting, they serve completely
different purposes. So a new type is defined.
Default left empty since it's an OS default (around {left: 10, bottom: 10} in my tests)
> Allow legalLabelInsets to be changed and animated

- README.md
- android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
- components/MapView.js
- ios/AirMaps/AIRMapManager.m
This pull request adds support for `takeSnapshot` on Android.
The takeSnapshot function was purposefully implemented on the AirMapModule class and not as a command on AirMapManager. The reason was that with using commands it is not possible to call the callback that is provided. The callback cannot be extracted from `ReadableMap`. This made it unsuitable for this specific function. I've taking inspiration from `react-native-view-shot` and was able to implement the functionality on the AirMapModule instead.
The region argument is not used on Android and the width and height are interpreted differently. This is because the `GoogleMaps.snapshot` doesn't take the size or region as input. This creates a feature difference with the iOS version.
Additionally, I've made `takeSnapshot` promise …
> Added support for taking snapshots on Android

- docs/installation.md
This adds a solution to fix the mismatch between the play-services in case the user wants to use a different version
This fixes #877,  #831 and #874 for all versions while keeping compatibility with projects using older version of play-services
> [doc, android] Adding section to fix gradle problems

- example/examples/AnimatedViews.js
The "Animating with MapViews" example (`./example/examples/AnimatedViews.js`) was broken as explained in #763. This small PR fixes it.
> Fix "Animating with MapViews" example – fixes #763

- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
Fixes a crash cause by calling animateToRegion on the map while it is still be initialized.
To reproduce:  
In the `componentDidMount` of the component that renders the `MapView` add a `    this._map.animateToRegion(region, 1500);`.
Basically on the native side we haven't initialized the `map` variable yet (which happens in `onMapReady`) so if that's the case we can't do an `animateToRegion` yet.
> [android crash]  Fix exception when animating region during initialization

- ios/AirMaps/AIRMapManager.m
Fixed issue #751 
When `fitToElements` is set to `true` from `ComponentDidMount` it causes a behaviour where callouts does not appear sometimes and if appear they are sometimes overlapped by other markers.
> Fixed issue #751.

- docs/mapview.md
add non-optional `animated` parameter to the docs, closes #958
> Update docs mapview.md for fitToSuppliedMarkers

- docs/installation.md
This adds Android SDK Build-tools 23.0.3 to the troubleshooting section for Android. This is required because react-native documentation (https://facebook.github.io/react-native/docs/getting-started.html) only specifies a requirement of Build-tools 23.0.1.
The build error if you don't have 23.0.3 installed is
```
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-maps'.
> Failed to notify project evaluation listener.
> failed to find Build Tools revision 23.0.3
> failed to find Build Tools revision 23.0.3
```
> Add Android SDK Build tools 23.03 to troubleshooting

- docs/installation.md
Added troubleshooting step for enabling Use Host GPU checkbox in AVD settings. It appears that Google Maps requires Open GL to be enabled and working on devices for it to draw the map. See https://github.com/airbnb/react-native-maps/issues/942
> Add 'Use Host GPU' troubleshooting step for Android

- ios/AirMaps/AIRMap.m
This addresses issue #991. This should allow for templateURL updates to display properly.
> Sets the map value for the AirMapUrlTile so that it can be updated properly

- ios/AirMaps/AIRMapMarker.h
- ios/AirMaps/AIRMapMarker.m
- ios/AirMaps/AIRMapMarkerManager.m
The issue relates to [getAnnotationView](https://github.com/airbnb/react-native-maps/blob/master/ios/AirMaps/AIRMapMarker.m#L68) method.
A tap gesture is added to `AirMapMarker` view in `AirMapMarkerManager` class which listens to tap/press events on annotation view as well as callout view. But when `shouldUsePinView` returns `true`, the annotation view on map is a `MKPinAnnotationView` instead of `AirMapMarker` and there is no tap gesture listener on this MKPinAnnotationView.
Now the Tap gesture is listened by the `AirMapMarker` class itself and gesture now added to MKPinAnnotationView as well.
> Fixed issue #286.

- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
Currently, on iOS the onMarkerPress callback includes the identifier of the map marker as an `id` property. Google Map markers do not store their identifier. This change aligns both platforms.
> Add id identifier to marker-press event on Android

- package.json
- scripts/update-version.js
Similar to `npm version`, but updates the version number in all the
files we need to.
Usage:
./scripts/update-version.js [major|minor|patch]
It will:
* Get current npm version.
* Determine what type of version bump: major, minor, patch
* Update the files:
* package.json
* android/gradle.properties
* react-native-maps.podspec
* react-native-google-maps.podspec
* Make Git commit.
* Create Git tag.
to: @lelandrichardson @gilbox 
cc: @ljharb
> Create `update-version` script to more easily update version

- docs/installation.md
`react-native link react-native-maps` should be used instead of simply `react-native link` because it may break, or double, manual linkings, especially for libraries that that do not work with `react-native link` (gl-react-native for example)
> specify `react-native link` command

- docs/installation.md
Add note about dealing with correcting the system image to use with the
emulator.
> Add one more tip to Android installation troubleshooting

- docs/mapview.md
Added this related to #1003 and probably. It is just a comment on the notes of `fitToCoordinates` related to the when is recommended to call this method. Due a crash on android if called from `ComponentDidMount`. 
This could be a temporal solution, till someone (I will try if i find the time for it) investigate why is it crashing the call in android in this specific case.
> Improve documentation for fitToCoordinates

- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
to: @gpeal 
Before this change, we were using the application context to get the app's current activity, which was then passed into `MapView.<init>`, which was sometimes crashing by being null. There was no need to pass the activity into this, so instead we are just passing in the react context (which won't ever be null).
Also I am removing the private setting of the react context on the manager instance, which is a memory leak. Now `pushEvent` requires that you pass the react context along with it.
Tested on several devices and seems to be good.
> Fix null activity crash

- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- example/android/app/build.gradle
to: @gpeal 
This is same as #1148 but applied to master.
The fix is to not use `getCurrentActivity()` as the context to pass into MapView. This can be null at times, but the context passed into the view manager will not be.
Additionally, this removes a memory leak with setting the react context to an instance property on the view manager.
Fixes #1147
> [Android] fix null activity crash

- android/build.gradle
to: @gpeal 
cc: @GantMan 
This allows the library to compile but will use whichever RN the
app is using and also allows it to pass POM verification on sonatype
which doesn't allow non-explicit dependencies.
I believe this can actually finally settle the gradle `:+` vs `:0.x` debate! This seems to work how we want it.
> Use provided as the gradle dependency

- android/build.gradle
- example/android/app/build.gradle
When using the current android studio with the current SDKs you have the problem that your app is on version 25 and you can not create a APK without adjusting the buildToolsVersion in the build.gradle
> Update the android buildToolsVersion to 25.0.0

- example/ios/AirMapsExplorer.xcodeproj/project.pbxproj
- ios/AirGoogleMaps/AIRGoogleMap.h
- ios/AirGoogleMaps/AIRGoogleMap.m
- ios/AirGoogleMaps/AIRGoogleMapManager.m
- ios/AirGoogleMaps/AIRGoogleMapMarkerManager.m
- ios/AirGoogleMaps/AIRGoogleMapPolygonManager.m
- ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m
- ios/AirMaps.xcodeproj/project.pbxproj
- ios/AirMaps/AIRMap.h
- ios/AirMaps/AIRMapCircle.h
- ios/AirMaps/AIRMapManager.m
- ios/AirMaps/AIRMapMarker.h
- ios/AirMaps/AIRMapPolygon.h
- ios/AirMaps/AIRMapPolygonManager.m
- ios/AirMaps/AIRMapPolyline.h
- ios/AirMaps/AIRMapPolylineManager.m
- ios/AirMaps/AIRMapUrlTile.h
- ios/AirMaps/RCTConvert+MapKit.h
- ios/AirMaps/RCTConvert+MapKit.m
Since https://github.com/facebook/react-native/commit/48f30eca7e3d4c239501de515a7cc35615ed6bd1 RCTConvert+MapKit was removed from React Native so this pulls in the relevant methods and renames `RCTConvert+MoreMapKit` to `RCTConvert+MapKit`. I checked that having these extension defined multiple times doesn't cause issues so this is fully backwards compatible.
> Use local RCTConvert+MapKit instead of the one in React Native

- android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
This is to revert part of PR#694 to fix the memory leak problem on android. 
It also has the patch from https://github.com/IjzerenHein/react-native-maps/commit/14ca6f73078a2e8dedccfeefe8a037d55f03c59c to avoid the crash on pause -- which is mentioned in #414
> issue#939, fix multiple-instance memory leak

- android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
java.lang.NullPointerException: Attempt to invoke virtual method
'com.google.android.gms.maps.Projection
com.google.android.gms.maps.GoogleMap.getProjection()' on a null object
reference
at com.airbnb.android.react.maps.AirMapView$13.run(AirMapView.java:643)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5289)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.ja
va:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
> Crash in our App fix

- ios/AirMaps/AIRMapMarker.m
addresses #436, parts of #553 
Problem: when using markers with a custom subview, `didSelectAnnotation` does not get triggered on tap events, unless you press on the outside edge of the marker (outside the subview but inside the marker)
Solution: 'marker-press' events manually call `selectAnnotation` on the marker's mapview
> fix onSelected event for markers with custom view

- components/MapView.js
- docs/mapview.md
- ios/AirMaps/AIRMap.h
- ios/AirMaps/AIRMapManager.m
On iOS, the user location annotation has a default and unsettable text `My Location`, as shown in issue #934.
Now you can add `userLocationAnnotationTitle` as a prop to `<MapView />` when `showsUserLocation` is true.
I had no prior experience in Objective-C so do let me know if the codes modified are dirty. Any other suggestions on the modified code are also welcome.
> Issue #934 Add customized user location annotation text

- components/MapPolygon.js
- example/examples/EventListener.js
- example/ios/AirMapsExplorer.xcodeproj/project.pbxproj
- ios/AirGoogleMaps/AIRGMSPolygon.h
- ios/AirGoogleMaps/AIRGMSPolygon.m
- ios/AirGoogleMaps/AIRGoogleMap.h
- ios/AirGoogleMaps/AIRGoogleMap.m
- ios/AirGoogleMaps/AIRGoogleMapManager.m
- ios/AirGoogleMaps/AIRGoogleMapPolygon.h
- ios/AirGoogleMaps/AIRGoogleMapPolygon.m
- ios/AirGoogleMaps/AIRGoogleMapPolygonManager.m
Related with https://github.com/airbnb/react-native-maps/issues/982 the onPress functionality was missing for Polygons using Google Maps on iOS.
This PR adds the missing functionality mentioned above with a new property `tappable` to enable tab events on Polygons (Overlays) since this is disabled by default (see [this](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_overlay.html#a45005ec17da8c14bd1978f5cf19d91c7))
You can test the onPress event in the example app under the 'Events (incomplete)' section:
> [iOS] Added onPress support for Polygons on Google Maps

- example/android/app/src/main/AndroidManifest.xml
- lib/android/src/main/AndroidManifest.xml
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
to: @mattshen @gpeal 
I addressed some of @gpeal's feedback from #1130 
So it looks like `onDestroy`, `onPause` and `onResume` are final methods, and so are not able to be overridden... which makes some of gabe's feedback impossible to implement.  As a result, this PR doesn't include that many changes... but LMK what ya'll think.
> Address PR feedback from #1130

- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirGoogleMaps/AIRGoogleMapMarkerManager.m
- lib/ios/AirGoogleMaps/AIRGoogleMapPolygonManager.m
- lib/ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m
- lib/ios/AirMaps/AIRMap.h
- lib/ios/AirMaps/AIRMapCircle.h
- lib/ios/AirMaps/AIRMapManager.m
- lib/ios/AirMaps/AIRMapMarker.h
- lib/ios/AirMaps/AIRMapPolygon.h
- lib/ios/AirMaps/AIRMapPolygonManager.m
- lib/ios/AirMaps/AIRMapPolyline.h
- lib/ios/AirMaps/AIRMapPolylineManager.m
- lib/ios/AirMaps/AIRMapUrlTile.h
- lib/ios/AirMaps/RCTConvert+AirMap.h
- lib/ios/AirMaps/RCTConvert+AirMap.m
This should fix #1168, I haven't reproduced the problem but my guess is that is uses the category in RN instead of the one in AirMaps.
cc @lelandrichardson
> Rename MapKit category to avoid conflicts with the one in RN

- lib/ios/AirMaps.xcodeproj/project.pbxproj
These files were [renamed](https://github.com/airbnb/react-native-maps/commit/4926f5b53fac8e1ab9aaf877e81048e262dee8aa) but the project file wasn't updated.
Fixes https://github.com/airbnb/react-native-maps/issues/1193
> pbxproj: RCTConvert+MapKit -> RCTConvert+AirMap

- docs/installation.md
The `lib` folder is missing from the documentation, adding it.
> Add missing the `lib` folder in the docs

- .npmignore
I get errors saying that the plugin "module-resolver" does not exist because the .babelrc is published with the react-native-maps package. This PR will ensure this is not published in the future and as to avoid this error.
> Add babelrc to npmignore

- example/examples/EventListener.js
- lib/components/MapPolyline.js
- lib/ios/AirGoogleMaps/AIRGMSPolyline.h
- lib/ios/AirGoogleMaps/AIRGMSPolyline.m
- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapPolyline.h
- lib/ios/AirGoogleMaps/AIRGoogleMapPolyline.m
- lib/ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m
- lib/ios/AirMaps.xcodeproj/project.pbxproj
This PR fixes the problem of not having the `onPress` event on Google Maps in iOS.
> [iOS - Google Maps] Add onPress support for Polyline

- docs/installation.md
Changing the reference to `AirMapExplorer` (incorrect) to `AirMapsExplorer` (correct) in the installation docs.
> Fixing reference to AirMapsExplorer in installation docs

- docs/marker.md
- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.h
- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m
- lib/ios/AirGoogleMaps/AIRGoogleMapMarkerManager.m
I added the rotation for the Google Maps provider on iOS. It was already working on Android.
I can't figure out how to do it with `MKAnnotationView` for the MapKit provider..
The rotation is in degrees, starting from 0 to 360.
> Add Marker rotation for Google Maps on iOS

- lib/ios/AirMaps.xcodeproj/project.pbxproj
In latest `0.15.1` release I have got an error in iOS build:
This occurs because the `AirMaps.xcodeproj` contains references to `AIRGMSPolyline.h` and `AIRGMSPolyline.m`  that were added by #1194 
I believe that `AirMaps.xcodeproj` should not contain any references to files from `AirGoogleMaps` folder.
After removing this files everything is ok 👍 
PS: This is the last thing that does not allow us to upgrade our project to react-native 0.44. I hope you will merge this PR and publish patch to npm 😊
> Remove AIRGMSPolyline.h and AIRGMSPolyline.m references from AirMaps.xcodeproj

- lib/components/MapCallout.js
- lib/components/MapCircle.js
- lib/components/MapMarker.js
- lib/components/MapPolygon.js
- lib/components/MapPolyline.js
- lib/components/MapUrlTile.js
- lib/components/MapView.js
Update the ViewPropTypes to match the last revision of React Native V0.44.0
> View.propTypes to ViewPropTypes (53905a5) - @bvaughn
https://github.com/facebook/react-native/releases
> Update from View.propTypes to ViewPropTypes to match RN v0.44.0

- example/examples/DisplayLatLng.js
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
This addresses #955 and #811 by doing the following:
- Add the missing `animateToCoordinate()` for Google Maps on iOS - I just noticed that @peterept recently create #1112 😄 but one issue I found when I was working on it was that UIView animation doesn't work. This means the `duration` argument is ignored. The solution was to use Core Animation, which I found here: http://stackoverflow.com/questions/15662148/controlling-animation-duration-in-google-maps-for-ios/15663039#15663039
- Add a new button to the "Tracking Position" example that uses `animateToCoordinate()`. It's very similar to the existing `animateToRegion()` button but is a useful test.
- Use Core Animation for `animateToRegion()`. This is backwards incompatible because the default duration of 500ms was being ignored before but …
> [iOS - Google Maps] Fix animateToCoordinate and animateToRegion

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
Sometimes AirMapView doDestroy is called before LifecycleEventListener onHostPause. This fixes https://github.com/airbnb/react-native-maps/issues/1358
> Fixes google map null pointer exception

- docs/installation.md
latest version of npm seems to be missing the command ```npm clean cache``` but ```npm cache clean``` seems to work. Might help copy-pasters like me.
> updates npm cache clean command

- docs/mapview.md
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirMaps/AIRMap.h
- lib/ios/AirMaps/AIRMapManager.m
> Add onMapReady callback

- lib/ios/AirMaps/AIRMapManager.m
This PR adds a MKTileOverlayRenderer for generic tile overlays in the mapView's `rendererForOverlay` delegate method.
Our application has a need to add tile overlays to the react native map from native code. This is already possible on Android, but iOS needs the correct renderer in the map delegate.
I am not sure if other developers have this use case, but I thought I'd propose this as an improvement. It won't affect any other behavior.
> [iOS] Allow adding of custom MKTileOverlays

- lib/android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
> Handle Android RN 0.47 breaking change

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
A variant of https://github.com/airbnb/react-native-maps/pull/1403 but for another lifecycle method, as proposed by @Nelrohd.
Another part of the fix for https://github.com/airbnb/react-native-maps/issues/1358 (which was closed prematurely)
> Attempt to fix crashes.

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
This happens if google play services version is lower than required. It is to fix issues#618
There are also other places checking if `map == null` before calling `startMonitoringRegion` or `stopMonitoringRegion` usually followed with another call, e.g.
```java
public void animateToRegion(LatLngBounds bounds, int duration) {
if (map != null) {
startMonitoringRegion();
map.animateCamera(CameraUpdateFactory.newLatLngBounds(bounds, 0), duration, null);
}
}
```
However, both ways of check map's nullability are lack of elegance.
> [Android Crash] skip region monitoring if map object is null

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
Fix the crashing of the application when a user presses on the map and the Google Play Services need to be updated or at the moment of the process of updating.
```
E/AndroidRuntime( 5908): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.Projection com.google.android.gms.maps.GoogleMap.getProjection()' on a null object reference
E/AndroidRuntime( 5908): 	at com.airbnb.android.react.maps.AirMapView$13.run(AirMapView.java:643)
E/AndroidRuntime( 5908): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 5908): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5908): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5908): 	at android.app.ActivityThread.main(ActivityThread.java:5264) …
```
> Fix the crashing of the application when Goole Play Services need to be updated

- lib/components/AnimatedRegion.js
It seems the animation function, `timing`, used in the `AnimatedRegion.spring` method should actually be `spring` to reflect the name of the function.
If this is intended, I'd suggest merely calling `AnimatedRegion.timing` from `AnimatedRegion.spring` instead of re-implementing it. I think this also would have the benefit of being more transparent for future readers of the code.
> Fix timing function used in AnimatedRegion.spring

- example/ios/Podfile
Remove `React` target from `Pods` xcproject.
As seen in https://github.com/facebook/react-native/issues/12814
> Fixed `Archive` configuration for iOS

- lib/components/MapView.js
- lib/ios/AirMaps/AIRMapManager.m
Fixes https://github.com/airbnb/react-native-maps/issues/1540 and https://github.com/airbnb/react-native-maps/issues/1507.
Sometimes it could happen that, when using initialRegion prop and moving on the map, we could just come back to our initial region for no reason. That's because we never set the initialRegion prop in the native code, but we set the region prop, while our component has the initialRegion prop.
> Fix initial region native prop

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
According to the Google Map iOS SDK [attribution requirements](https://developers.google.com/maps/documentation/ios-sdk/intro#attribution_requirements) you need to include their legal notice in your app. This PR exposes this text as a constant. There might be a nicer way to use this but it can be used like this:
```js
const noticeText = Platform.select({
ios: () => NativeModules.AIRGoogleMapManager.legalNotice,
android: () => NativeModules.AirMapModule.legalNotice,
})();
```
> Add Google Maps legalNotice constant

- lib/components/MapMarker.js
Add ability to load marker images from drawable.
There are some methods to load drawables as markers in the AirMapMarker class but it seems that it was impossible to use those. Here, we just have to pass the drawable name to the image prop, and it will load our drawable.
It can fix some memory issues when you want to use a custom view for a big amount of markers using local images.
> Add ability to load marker image from drawable

- lib/components/MapView.js
This is to provide support for RN <0.44 where ViewPropTypes was introduced
> Fall back to View.propTypes if ViewPropTypes is not available (#1473)

- lib/components/MapView.js
Reverts JS changes made in #1563 which broke initialRegion on iOS,
causing the map to display a region centered around 0, 0.
> [MapView] revert initialRegion change

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
Fixes an error on Android release mode when the Map.Marker has children.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
```
From https://github.com/Geor23/react-native-maps/commit/a83c04a4ebb1697e17cf2e77a2f26e9142ea5cc7
Closes https://github.com/airbnb/react-native-maps/issues/907
> [MapMarker] fix android release crash on custom marker

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
As per https://developers.google.com/android/reference/com/google/android/gms/common/GooglePlayServicesUtil#getOpenSourceSoftwareLicenseInfo(android.content.Context) this information does not need to be displayed in app.
> Remove legalNotice from android AirMapModule

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
This is to fix https://github.com/airbnb/react-native-maps/issues/245
This cannot be easily reproduced, and only happens in our released app from time to time (not often). 
The safest way is to check width and height before calling `newLatLngBounds(boundsToMove, width, height, 0)`
> fix rare android crashes when map size is 0

- package.json
`npm install` / `yarn install` auto updates to `16.0.0-alpha.13` which
breaks the proptypes import.
This affects the `example` app:
Removing caret to prevent auto update to `alpha.13`.
For more information: https://github.com/facebook/react-native/issues/14454
> Remove caret from "react": "^16.0.0-alpha.12"

- docs/mapview.md
- example/examples/DisplayLatLng.js
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirMaps/AIRMapManager.m
First of all, thank you all guys for maintaining this awesome repo, it helps a lot to get started using Maps with ReactNative.
For those who are not familiar with the names of the functions this PR adds, Bearing is the direction or course of motion itself, and Viewing angle is the angle of the camera attached to the MapView.
This PR allows you to change the bearing dynamically (for example for apps that requires navigation features like Waze does) and also can change the map view angle (so you get like building shape kinda 3D).
~~This PR adds support for IOS (for now,  I plan to do for Android soon). I am pushing this so if anyone can help with feedback or code for Android I appreciate it 👍.~~
Updated: This PR adds full support for IOS (both native MapKit map and Google Maps) and Android. …
> Adds support to animateToBearing and animateToViewingAngle ( IOS + Android )

- index.d.ts
Fix a bug I found after submitting PR #1601.
I was getting this error:
`[TS] Exports and export assignments are not permitted in module augmentations.`
Thanks!
> Fixed a TypeScript Error

- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
Fixes Warning for react-native > 0.49
> Module AIRGoogleMapManager requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
> Fix React Native 0.49 requiresMainQueueSetup

- react-native-google-maps.podspec
XCode 9 together with RN 0.49.1 throws the error that GoogleMapsBase could not be found. This PR introduces a workaround based on this PR: https://github.com/googlemaps/google-maps-ios-utils/pull/20/files
Fixes issue #990 and #1722
> Workaround for "GoogleMapsBase not found" issue

- lib/components/MapView.js
Right now it's not possible to call `fitToCoordinates` without an `options` parameter, even though defaults are defined in the function body.
This commit set the default value of the `options` parameter of  to an empty object, allowing one to call the function without it _(and with respect for the defaults)_.
> Allow fitToCoordinates to be called without options parameter

- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirMaps/AIRMapManager.m
(Closes #1793)
Also: Closes #1776, Closes #1696, Closes #1680, Closes #1605)
Probably closes more issues related to iOS, panning and scrolling.
---
The issue is that on Android, the onMapReady comes from the native onMapReady event, which occurs when Google Play Services first provides a Google Maps view.
But on iOS - it happened whenever rendering has finished - which is a completely different interpretation, and misses the point of just doing the initial stuff like `initialRegion`/`region`.
> Fixed onMapReady event on iOS to resemble onMapReady on Android

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/android/src/main/java/com/airbnb/android/react/maps/RegionChangeEvent.java
`OnCameraChangeListener` is deprecated and should no longer be used. This PR adds support for the new more powerful APIs and removes the old (quite hacky..) region detection code. This fixes various issues and paves the way for distinguishing between gestures and manual/programatic animations at the same time.
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraChangeListener
This PR fixes #1709 and I'm pretty sure it also fixes:
- #349
- #1379 
- #1591 
- #134 
- #846 
- #459
> Added support for new Android camera movement APIs

- docs/mapview.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
Adds the ability to prevent scrolling outside of a set of boundary coordinates. Pass in two `LatLng` points, preferably a North East point and a South West point (In testing any two points worked and the overlapping area formed the desired region).
- Works on Android and Google Maps for iOS
- Solves #1424  (my issue 🎉 ) 
- [Android Docs](https://developers.google.com/maps/documentation/android-api/views#restricting_the_users_panning_to_a_given_area)
- [iOS Docs](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view.html#af18afcf5b4eab9edf2b700734d2c7f07)
> Add support to set map boundaries

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
Related to https://github.com/airbnb/react-native-maps/pull/1587
> [AirMapManager] Update MapBuilder for getCommandsMap to support all entries

- react-native-google-maps.podspec
this is to resolve compile error: Property 'cameraTargetBounds' not found on object of type 'AIRGoogleMap *'
> update GoogleMaps dependency to 2.5.0

- docs/polygon.md
Because there is an undocumented props `tappable`
> #1859 onPress event for Polygon doesn't work on iOS

- README.md
- example/examples/CustomTilesLocal.js
- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapLocalTile.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapLocalTileManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
- lib/components/MapLocalTile.js
- lib/components/MapView.js
- lib/ios/AirMaps.xcodeproj/project.pbxproj
- lib/ios/AirMaps/AIRMap.m
- lib/ios/AirMaps/AIRMapLocalTile.h
- lib/ios/AirMaps/AIRMapLocalTile.m
- lib/ios/AirMaps/AIRMapLocalTileManager.h
- lib/ios/AirMaps/AIRMapLocalTileManager.m
- lib/ios/AirMaps/AIRMapLocalTileOverlay.h
- lib/ios/AirMaps/AIRMapLocalTileOverlay.m
- lib/ios/AirMaps/AIRMapManager.m
Added support for locally stored tile overlay similar to UrlTile component. Usage example in CustomTilesLocal.js file, but basically one just adds tile overlay within the map:
`<MapView ... >`
`<LocalTile`
`pathTemplate="/path/to/localy/stored/tiles/{z}/{x}/{y}.png"`
`tileSize={256}`
`/>`
`</MapView>`
Path just points to the path where tiles are stored.
> #255 LocalTile overlay

- lib/components/MapView.js
I noticed that 
props.region and props.initialRegion are always come as null. (even if set for `<MapView />`)
This change gives ability to set `region` and `initialRegion` to something that come from the top. 
Also it causes big performance issue on RN side when these props are null, (I'll try to mitigate that with different PR)
> fixed region/initialRegion null overrides of this.props

- example/examples/AnimatedMarkers.js
Fix for 'Animated.Region undefined constructor' in recent react-native version. 
Solved by using MapView.AnimatedRegion instead of Animated.Region
> Update for Animated.Region #24 Fix on the AnimatedMarkers Example 

- example/examples/AnimatedMarkers.js
I propose to change an example in docs, as it wasn't working correctly.
- AnimatedRegion is property of MapView
- make sure animate method is executed in correct context
> Fix example with animated markers

- lib/ios/AirMaps/AIRMapManager.m
Hi, this fixes onMapReady no longer getting called correctly in v0.18.x.
Due to this commit (https://github.com/airbnb/react-native-maps/pull/1797/files#diff-8a72baa08460d22c71989ddcbf76d49f), `onMapReady` was only called when the very first MapView was rendered for the very first time. After unmounting/mounting, or rendering any other MapView, onMapReady would be never called.
> Fixed onMapReady no longer getting called on iOS

- docs/polyline.md
The type for `lineJoin` was wrong, the default value was missing and the text for `lineJoin` and `lineCap` did not explain the possible values.
> Corrected doc text for Polyline

- lib/components/MapPolyline.js
``lineJoin`` and ``lineCap`` should have default value ``round``, according to docs.
> corrected default value to ``round``

- docs/installation.md
An emphasis to open .xcworkspace instead of .xcodeproj was added to documentation.
>  Add openning the .xcworkspace file instead of .xcodeproj to documentation

- docs/mapview.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirMaps/AIRMap.m
Right here, right now, explaining this is a "more is less" situation :-)
> New methods to convert between LatLng and Point

- lib/ios/AirMaps/AIRMapMarker.m
For use with tooltip={true}. Ugly, but works.
> Fix callouts appearing behind markers

- lib/ios/AirMaps/AIRMapPolylineRenderer.m
The new gradient polyline was not always completely visible, because the Matrix transform in the paths was not applied correctly. This happened because the segments were cached and could have the wrong matrix transform applied to them (this happens implicitely during calls to CGPathMoveToPoint & CGPathAddLineToPoint). This could cause the line to not be complete visible, because it was drawn behind the map-tile. (see screenshots below)
Also, I’ve witnessed some rare crashes due to the caching of the segments. Apparently, the class was accessed from multiple threads which led to threading issues. Removing the segments cache fixed this problem as well.
**Before fix:**
**After fix:**
> Fixed gradient polyline not always fully drawn + stability issues

- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
This is an attempt to fix several issues with google maps in iOS. Mainly -
- Fix onMapReady not getting called after first time
- Fix initialRegion lat/lng delta not setting properly
- Fix setRegion method getting called even when map is not ready
- Prevent onRegionChange/ onRegionChangeComplete event until initialRegion or region is set.
> iOS google map fixes

- README.md
- lib/components/MapUrlTile.js
- lib/ios/AirMaps/AIRMapUrlTile.h
- lib/ios/AirMaps/AIRMapUrlTile.m
- lib/ios/AirMaps/AIRMapUrlTileManager.m
Exposing the maximumZ property from MKTileOverlay to javascript so that you can overzoom on custom tiles without the tiles disappearing.
> Exposing the maximumZ property to AIRMapUrlTile

- package.json
This will remove warnings like this when installing:
```
warning " > react-native-maps@0.20.1" has incorrect peer dependency "react@16.0.0".
warning " > react-native-maps@0.20.1" has incorrect peer dependency "react-native@0.51.0".
warning " > react-native-maps@0.20.1" has unmet peer dependency "prop-types@^15.5.10".
```
> Broader peer dependency support

- CHANGELOG.md
- docs/installation.md
- lib/android/build.gradle
As recommended by the Android Developer Document [Gradle Tips &amp; Tricks](https://developer.android.com/studio/build/gradle-tips.html) (See "*Configure project-wide properties*"), if the hosting application defines the following properties in their root `build.gradle`,  peer modules (like `react-native-maps`) can align its dependencies as requested:
```diff
buildscript {...}
allprojects {...}
/**
* Project-wide gradle configuration properties for use by all modules
*/
+ext {
+    compileSdkVersion   = 26
+    targetSdkVersion    = 26
+    buildToolsVersion   = "26.0.2"
+    supportLibVersion   = "26.1.0"
+    googlePlayServicesVersion = "11.8.0"
+    androidMapsUtilsVersion = "0.5+"
+}
```
```diff
android {
+    compileSdkVersion rootProject.compileSdkVersion
+    buildToolsVersion …
```
> Check for presence of project-wide gradle configuration properties

- lib/components/MapView.js
- lib/ios/AirMaps/AIRMap.m
- lib/ios/AirMaps/AIRMapManager.m
* Fixed typo "coordinateFromPoint"
* Moved coordinateForPoint/pointForCoordinate from AirMap to AirMapManager
* Fixed how resolve/reject are handled
I have tested on iOS. Yet not confirmed on Android. If anybody can confirm this works on Android, I think this PR is good to go.
> Fix for pointForCoordinate and coordinateForPoint

- README.md
- docs/mapview.md
- example/App.js
- example/examples/OnPoiClick.js
- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
Exposes the onPoiClick event to react-native-maps wrapper.
It send back the location of the poi, the name and the googleId (docs updated)
I haven't dug in IOS implementation yet since I'm more confortable with android. But I'll definitely do it through a next PR ! (or if anyone is keen to, feel free)
Let me know if any other steps need to be done 👍
> add Android support for onPoiClick

- docs/installation.md
No
Improves the installation guide:
- It now tells the developer to get a separate android api key (unclear before)
- Fixed a path that was using backslashes vs forward slashes
I read it. It includes the things I needed to correct when installing the module for the first time.
> Tell user to get separate api key for android + forward slashes in path

- lib/ios/AirMaps/AIRMap.m
Not currently.
The circle will not re-render when radius or center changes. This is due to a simple mistake in AIRMap.m
https://github.com/react-community/react-native-maps/pull/187#issuecomment-373427864
Tested by creating a project in which the radius and lat/lng values can be changed dynamically. When these values change, the corresponding re-render updates the view to match the new values.
> Fixed re-render not updating MapView.Circle component in UI when radius or center coordinates change.

- docs/installation.md
- example/ios/Podfile
https://github.com/react-community/react-native-maps/pull/2065
This clearly wasn't tested - the Podfile contains a syntax error, which causes `pod install` to fail.
Uses Ruby-style comment in the Podfile & example doc.
Followed https://github.com/react-community/react-native-maps/blob/master/docs/examples-setup.md and it works now after this change.
> Fix example project setup

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
No.
On Android, add a [vector drawable resource](https://developer.android.com/guide/topics/graphics/vector-drawable-resources.html) to the native code. ([Here](https://github.com/googlesamples/android-topeka/blob/master/app/src/main/res/drawable-v21/ic_cross.xml) is a sample if you need one.) Then, try to use it as the {{marker}} parameter. Previously, an exception would be thrown; with this PR, it now works:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
at com.airbnb.android.react.maps.AirMapMarker.getIcon(AirMapMarker.java:330)
at com.airbnb.android.react.maps.AirMapMarker.createMarkerOptions(AirMapMarker.java:360)
at com.airbnb.android.react.maps.AirMapMarker.getMarkerOptions(AirMapMarker.java:29 …
```
> permit android vector drawables to be used as markers

- docs/installation.md
- lib/android/build.gradle
Further details on Gradle 3.0.0+ https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations
No.
https://github.com/react-community/react-native-maps/issues/2095
Also fixing installation.md which had the old gradle configuration and not the new one.
> Updated gradle configuration for gradle 3.0.0+

- docs/mapview.md
No
https://github.com/react-community/react-native-maps/issues/2120
Just added mapPadding to mapview docs as it's already been implemented, and it quite useful for solving various problems.
1. Go to the Docs for mapview
2. ctrl + f "mapPadding"
> Add mapPadding to mapView docs

- docs/mapview.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
No
This adds a check to whether the returned location is authentic or mocked
Tested it on my application where I am checking for mock providers
1. Set showsUserLocation={true} in MapView component
2. Set 'google' as your map provider
3. Listen for onUserLocationChange which will return a callback with lat,long,speed,accuracy & boolean for isFromMockProvider
(Works only for Android)
I have tested this on Android (real device)
> Add Mock Provider boolean on each location update

- index.d.ts
According to specs at https://github.com/react-community/react-native-maps#take-snapshot-of-map
No.
None. It adds typings.
Tested on all platforms by modifying the typings.
> Add takeSnapshot method to MapView type definitions

- index.d.ts
I think so, but this PR is updated and more refined.
Mainly, event interface and missing methods and properties.
Tested with VS Code in real work, but not all the typings (We are not using all).
> Typings for v0.21.0

- lib/ios/AirMaps/AIRMapLocalTileOverlay.m
- lib/ios/AirMaps/AIRMapManager.m
We noticed these warnings when using this library inside Expo. Changed NULL to 0 for the NSStringCompareOptions flag; cast the NSIntegers to long when using as a string format argument; removed unused variable zoomLevel.
Not as far as I can tell.
There are some annoying compiler warnings in Xcode and this makes them go away.
I compiled the lib.
> Fix Xcode warnings for format, pointer type, unused var

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapUrlTile.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapUrlTileManager.java
No.
Fixing a compile issue of the Android version. I did not understand exactly what the (merged) PR #2136 does, but it breaks the Android java build with this error(s):
```
AirMapUrlTileManager.java:50: error: ';' expected
view.setMinimumZ(minimumZ)
AirMapUrlTile.java:32: error: cannot find symbol
if(this.maximumZ && zoom > maximumZ) {
```
- Use the current master of react-native-maps (for example with `yarn upgrade react-native-maps@react-community/react-native-maps#master`)
- Build your android app with `react-native run-android`
- This fails with the error above. With this changes it compiles again.
> Fix compile issues in Android (; expected and cannot find symbol)

- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
no
https://github.com/react-community/react-native-maps/issues/2203
every location is have timestamp and it's now received on RN side.
> Fix https://github.com/react-community/react-native-maps/issues/2203

- lib/components/MapView.js
ref. https://github.com/react-community/react-native-maps/pull/2181
> Apple are now rejecting app submissions without an explanation of why you need to user's location.
No
> Explaining a required step for location tracking, which will prevent Apple rejecting an app 
How did you test this PR?
I just added  comment. No code changes.
> Add comment about NSLocationWhenInUseUsageDescription

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlay.java
Nope
When `<Overlay/>` component is unmounted before the image had a chance to load (either a large image, or slow internet connection), after image finishes loading overlay is still rendered, and cannot be removed afterwards.
There was a bug on Android which didn't cancel image rendering after removing from map. My change erases map reference, thus avoiding this bug.
Tested on several Android devices, does not seem to affect iOS.
> Fix overlay removal bug

- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
No
Changes to these functions that did not reflect in both providers. Currently the API is broken - expecting callback in GoogleMaps and returning Promise in Air. While the docs says it returns Promise.
Written simple code with `await` to print results of both functions, in Air and Google provider.
> Fixed `pointForCoordinate`/`coordinateForPoint` Promises in iOS (#2039, #2061)

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolygon.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolygonManager.java
No.
https://github.com/react-community/react-native-maps/issues/1002
1. Create a `Polygon` and tap on it on Android.
2. Observe `onPress` event from Map.
3. Add `tappable` prop to polygon.
4. Observe lack of `onPress` event from Map.
> respect `tappable` prop on android

- lib/components/MapCircle.js
- lib/components/MapMarker.js
- lib/components/MapPolygon.js
- lib/components/MapPolyline.js
No
Using react-native's `ColorPropType` to validate all color props more accurately.
More specifically I'm doing this to avoid getting yellow box alerts when using different formats for colors. For instance, using `setNormalizedColorAlpha()` I have colors defined as integers in my app.
Just tested against my app, both in iOS and Android. Colors still work/no more alerts.
> Fix color prop types

- lib/ios/AirGoogleMaps/AIRDummyView.h
- lib/ios/AirGoogleMaps/AIRDummyView.m
- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m
- lib/ios/AirMaps.xcodeproj/project.pbxproj
Nope
This class makes the library difficult to vendor because it has no `AIR*` class prefix. It's nice to keep this library easily vendorable so that we can make sure Expo always has the newest version.
Rebuilt the native lib after renaming the class. There are no JS methods that reference this class.
> [iOS] Prefix DummyView class

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- lib/android/src/main/java/com/airbnb/android/react/maps/ImageReader.java
No
Expo uses the `asset://` scheme to load images from the app's bundle on Android. This is supported by Fresco (http://frescolib.org/docs/supported-uris.html) so we can simply add the new scheme to the list that we load using Fresco.
Verified that bundled assets in Expo work with the Marker component by applying this diff locally.
This should also work everywhere else we allow assets with the file:// scheme.
> Support the asset scheme for images

- docs/mapview.md
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
No.
https://github.com/react-community/react-native-maps/issues/2215
Compiled for iOS Simulator in XCode 9.3.
> Fix for compile error (#2215).

- lib/ios/AirMaps/AIRMapMarker.m
Not as far as I can tell
`AIRMapMarker`'s implementation file contains a few global variables, some of which appear to be mistakes (they're being used as though they were instance variables of AIRMapMarker, so I made them actually be instance  vars) and one which is a legitimate constant that I prefixed with `AIR`. These global symbols prevent the library from being vendored (e.g. for Expo) because they collide with other copies of the library. This solves that.
Build the project and include it as a vendored library with other copies of itself.
> [iOS] Prefix or eliminate globals in AIRMapMarker

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
No
On Android, using Google Maps, markers with custom views/images are not being updated correctly when other properties are changed (mainly coordinates). Sometimes markers are not draw anymore, until the child view/image is changed.
#1611 and #2048 are related.
1. Create a simple app with a MapView and 3 or more markers that have distinct views for normal/selected states with distinct sizes.
2. After MapView first rendered, dispatch changes to the markers coordinates and selected state (use a timer, button or marker touch event).
3. Expect markers to not update or disappear from map after a couple of changes.
4. Apply this patch and markers update as expected.
- Which platform/api: Android & Google
- Did you test this on a real device, or in a simulator? Simulator and Real device
> Fix custom marker updates on android #1611 #2048

- lib/ios/AirMaps/AIRMapMarker.m
Don't think so. This is an open issue.
https://github.com/react-community/react-native-maps/issues/1671
I have tested my changes on iOS Simulators (iOS 11 and iOS 10)
> zIndex doesn't work when the map moves in iOS 11

- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m
No
Explicitly mentioning self warning
Built application and warnings went away
Fixes the following warnings that I saw when building an application that used this package:
```
13:05:49]: ▸ ⚠️  /Users/kyledecot/code/root-react-native/node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m:226:72: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended be]
havior [-Wimplicit-retain-self]
[13:05:49]: ▸ if (_iconImageView) [_iconImageView removeFromSuperview];
[13:05:49]: ▸            ^
[13:05:49]: ▸ ⚠️  /Users/kyledecot/code/root-react-native/node_modules/react-native-maps/lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m:226:89: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended be]
havior …
```
> Fixes warnings about self

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
I didn't find any open issues or PR regarding this.
#2315
It affects all Android platforms by skipping the permissions check if you just want to disable the buttons.
Tested on a live device running Oreo.
> Fix disabling the toolbar and my location button

- README.md
How to overlay other React components on top of the `MapView`. This was not clear from the documentation and took some research to find a solution.
No, this is to make it clear in the documentation.
Documentation for overlaying components on the MapView
I found multiple other repos that utilise the same approach.
> Adding overlaying components details

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/android/src/main/java/com/airbnb/android/react/maps/ViewAttacherGroup.java
Nope.
This is related to the following issues:
#1870 #2105 #2048 
The REAL problem with displaying images inside the markers in Android, is not a bug in Fresco as claimed in some issues. It's that Fresco depends on the `onVisibilityChanged(...)` event to be called. And that's a protected method. And is propagated by `dispatchVisibilityChanged(...)` to the whole subview hierarchy. `dispatchVisibilityChanged` is protected too. And it depends on `mAttachInfo` etc.
So fiddling with Reflection is not an option as it counts on too many private stuff to not change in Android's core.
The solution I propose here is having a semi-invisible ViewGroup and add the markers' views to it, so it is properly "visible".
I'm calling it semi-invisible because setting visibility to INVISIBLE/GONE will again …
> Let onVisibilityChanged() be called on children (mainly fixes Image issues)

- docs/marker.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- lib/android/src/main/java/com/airbnb/android/react/maps/ViewChangesTracker.java
No
This is related to the following issues:
#1870 #2105 #2048 #2082
In my own project, with a progressing pie animation inside the marker.
I've also made sure that tracking stops when the marker is removed from the map etc.
iOS has the `tracksViewChanges` property which causes re-renders of the markers all the time, and slows down performance of the map greatly. 
Still, it is very handy especially given the async nature of React.
As many times the first images cached is of a blank component, it is very useful to use `tracksViewChanges=true` and then set it to `false` when `componentDidUpdate` is hit.
Another issue is loading images. Assuming the image loading issue will be fixed one day - we will still want `tracksViewChanges` and disabled that when `onLoadEnd` hits.
We could even start …
> Implemented `tracksViewChanges` for Android

- lib/ios/AirMaps/AIRMapManager.m
No
coordinateForPoint/pointForCoordinate in AirMaps are working differently than Google Maps. The coordinates are lat/lng instead of latitude/longitude, which is a mistake and is incompatible with this library.
Tested on an iOS 11 simulator, my own project, while trying AirMaps.
> coordinateForPoint/pointForCoordinate worked with coordinate shorthands on AirMaps

- package.json
No.
This PR will fix peer dependencies warnings when you run `npm install` on the projects which are using React Native 0.56.0(or later). This relates to #2332 .
in my project,
- remove react-native-maps from package.json.
- remove `node_modules`
- run `npm install` again
- run `npm install <relative path to react-native-maps> --save`
- confirm warning messages related to react-native don't appear.
However, it doesn't solve the warning around @babel-core@7.0.0-beta.38(required by @babel/plugin-check-constants@7.0.0-beta.38).
> Fix peer dependencies warnings

- docs/marker.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/android/src/main/java/com/airbnb/android/react/maps/ViewAttacherGroup.java
- lib/android/src/main/java/com/airbnb/android/react/maps/ViewChangesTracker.java
- lib/components/MapMarker.js
- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.h
- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m
- lib/ios/AirGoogleMaps/AIRGoogleMapMarkerManager.m
No
Performance improvements for #2477 #1870 
Full project
> Performance improvements for tracksViewChanges

- docs/mapview.md
- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirMaps/AIRMapManager.m
No.
Adds the `edgePadding` option to the `fitToSuppliedMarkers` function which is supported by Google Maps on both, iOS and Android. (no support for Apple Maps as the [native function](https://developer.apple.com/documentation/mapkit/mkmapview/1452309-showannotations) doesn't support this option).
The feature has been requested in those two issue and I had another use case on a personal project where I had to use a workaround using `fitToCoordinates`:
https://github.com/react-community/react-native-maps/issues/780
https://github.com/react-community/react-native-maps/issues/876
Another issue is requesting it for the function `fitToElements ` which should be an easy addition if this PR gets accepted:
https://github.com/react-community/react-native-maps/issues/922
Tested on real devices: …
> add edgePadding to fitToSuppliedMarkers function

- docs/mapview.md
- example/App.js
- example/examples/IndoorMap.js
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.h
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
PR #2189  , it has no return when Indoor Building is out of focus.
Added new events onIndoorBuildingFocused(also return empty array when building is out of focus), onIndoorLevelActivated.
Added command setIndoorActiveLevelIndex
Added new example for Indoor Map.
How did you test this PR?
All new features are for Google Map.
Tested on Android emulator (Nexus 5), iOS Simulator (iPhone X), real Android device (HTC U11), real iOS device (iPhone 6S) by running example.
> Add custom indoor picker level

- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirMaps/AIRMapManager.m
Fixes https://github.com/react-community/react-native-maps/issues/2513
https://github.com/react-community/react-native-maps/pull/2520
seems to fix the same issue
https://github.com/react-community/react-native-maps/issues/2513
iOS simulator. Builds were failing without this fix.
> fix fitToSuppliedMarkers function

- docs/installation.md
Checked open PRs for keywords 'docs' and 'documentationä. None found.
Not relevant.
None. This is a general improvement to the documentation.
The PR does not contain executable code. 
No executable code. However, I spent the entire day debugging the maps build for iOS and decided to share the lessons learned. 
This PR contains updates for the installation guide:
- Gave the installation documentation a good formatting scrub.
- Revised the troubleshooting section
- Documented clearly that the library ships with two map backends for iOS (was not clear to me).
View the proposed version at:
https://github.com/keksipurkki/react-native-maps/blob/feat/update-docs/docs/installation.md
Thanks for your good work!
> Improve installation docs

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
No.
I haven't created an issue for it, but seems to be the same issue found here:
https://github.com/react-community/react-native-maps/issues/2447
Error it fixes is the following, which for me personally occurred when re-rendering with the map with a partially different set of Markers.
For performance reasons in my project on render only markers that are within the specified region are returned with render, with the map re-rendering markers using `onRegionChangeComplete`. With small changes it is generally fine however I found when animating a region change where a lot of markers change this crash would occur.
This simple change in the java code fixed the issue for me.
I only have this issue on Android, and I could consistently replicate the crash on a suite …
> Fix for “The specified child already has a parent”

- docs/mapview.md
> update to clarify cacheEnabled is apple maps only

- package.json
No.
Babel-plugin-module-resolver and babel-preset-react-native are included as runtime dependencies. As far as I can see they are only referred from .babelrc which is also in .npmignore, so they are not used by end users who install react-native-maps as npm module. However, these deps have quite a lot of transitive dependencies. This PR moves them to devDependencies to spare end users from downloading them and bloating the node_modules.
I have searched the code base, and not found any other use for these two deps than .babelrc, which is excluded from npm published version.
> Move babel-plugin-module-resolver and babel-preset-react-native to devDependencies

- docs/mapview.md
- example/App.js
- example/examples/AnimatedNavigation.js
- example/examples/CameraControl.js
- example/examples/DisplayLatLng.js
- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapModule.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirGoogleMaps/RCTConvert+GMSMapViewType.h
- lib/ios/AirGoogleMaps/RCTConvert+GMSMapViewType.m
- lib/ios/AirMaps/AIRMap.h
- lib/ios/AirMaps/AIRMap.m
- lib/ios/AirMaps/AIRMapManager.m
- lib/ios/AirMaps/RCTConvert+AirMap.h
- lib/ios/AirMaps/RCTConvert+AirMap.m
No.
There is currently no way to control the camera via props.
I tested the example that comes with the PR on Android and on iOS with MapKit + Google Maps. I further tested the examples that have been updated as part of the PR on those platforms.
It is currently not possible to control things like the viewing angle, or the bearing, via props. In addition, the set of imperative methods to control the camera as they exist feel to me a bit as if they have grown over time, maybe just focussing on those parts the contributor needed to solve their problem at hand.
On the other hand, both the Apple Maps SDK as well as Google Maps support a flexible powerful camera system, which we can (and should) expose more directly.
One related problem is that the new `animateToNavigation` lacks the ability …
> Provide a camera system

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
No, it doesn't.
Fix Android app crash because building.getActiveLevelIndex() return index that out of bounds of 
the building when map found a building but showsIndoors is false. Exception error message as below
`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
length=8; index=-1
java.util.ArrayList.get (ArrayList.java:439)
com.airbnb.android.react.maps.AirMapView.onIndoorLevelActivated (AirMapView.java:1112)`
Tested on Android emulator (Nexus 5), real Android device (HTC U11),  iOS Simulator (iPhone X), real iOS device (iPhone 6S) by running example.
> [Android] Fix app crash in Android if building found but cannot getActiveLevelIndex

- index.d.ts
Fix below errors:
- 'setCamera', which lacks return-type annotation, implicitly has an 'any' return type.
- 'animateCamera', which lacks return-type annotation, implicitly has an 'any' return type.
No
No
Yes, I did `tsc`
> Fix type definition error

- lib/ios/AirGoogleMaps/RCTConvert+GMSMapViewType.m
Fixed a bug that
zoom and heading will always be 0 if they are not included in animateCamera with iOS GoogleMap.
For example
```
mapView.animateCamera({ zoom: 10 })
// zoom: 10
mapView.animateCamera({
center: {
latitude: xxx,
longitude: xxx
}
})
// zoom: 0!
```
NO
NO
Tested on iOS simulator with google maps
> [iOS GoogleMap] Fix animateCamera

- index.d.ts
- lib/components/MapView.js
- lib/ios/AirMaps/AIRMapManager.m
No
This PR extends by previous PR https://github.com/react-native-community/react-native-maps/pull/2571 based on disscussion which starts here https://github.com/react-native-community/react-native-maps/pull/2571#issuecomment-440993046
This PR just brings helper method which calculates bounding box from region, because it is much faster than accessing native module. But could be used only in some cases when is region available.
You can see screenshots in this comments, https://github.com/react-native-community/react-native-maps/pull/2571#issuecomment-440956375 where is comparison native vs react side.
> Calculate bounding box from region

- index.d.ts
- lib/components/MapUrlTile.js
- lib/ios/AirMaps/AIRMapUrlTile.h
- lib/ios/AirMaps/AIRMapUrlTile.m
- lib/ios/AirMaps/AIRMapUrlTileManager.m
There are some related open issues talking about tile size. And there is one issue asking for PR of tile size props. So here it is this PR trying to resolve these issue. 
Support for tileSize in UrlTile props https://github.com/react-native-community/react-native-maps/issues/2567
On iOS, use the sample code to initialize a map view with URL tile on it. And the tile's size should be other than 256 to trigger the issue that on iOS default tile size (256 * 256) is always used. 
Then in your UrlTile component, add a tileSize prop with the expected tile size number and run your app again. Now you should see the tile being correctly rendered according to your tile size prop.
> Adding tileSize props for iOS.

- lib/android/build.gradle
As of now the googlePlayServicesMapsVersion variable defaults to "DEFAULT_GOOGLE_PLAY_SERVICES_VERSION" which is an unpublished version of maps - 16. 0.1, it needs to default to "DEFAULT_GOOGLE_PLAY_SERVICES_MAPS_VERSION" instead which is 16.0.0
No, no other PR's have been submitted at the time of writing.
https://github.com/react-native-community/react-native-maps/issues/2652
Ran the sync before and after fixing with it symlinked, my PR fixes the issue with downloading the correct play services version.
> Defaults to the map services version instead of play services

- CHANGELOG.md
- example/ios/Podfile.lock
- lib/android/gradle.properties
- package.json
No!
https://github.com/react-native-community/react-native-maps/issues/2648
Not at all ;-)
> Release 0.23.0

- docs/polygon.md
- docs/polyline.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolyline.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapPolylineManager.java
No
Fixes #2591 
1. Create a `Polyline` and tap on it on Android.
2. Observe `onPress` event from Map.
3. Add `tappable` prop to `Polyline`.
4. Observe lack of `onPress` event from Map.
> Implement 'tappable' prop on polyline for Android

- lib/components/decorateMapComponent.js
fixes #2620 YellowBox warning on react-native 0.58.0-rc.1
No
#2620
1. Update ios application that use react-native-maps to react-native 0.58.0-rc.3
2. Open screen with any map component
3. Check that no warning after this PR applied
> Fix warning in RN >= 0.58

- lib/android/build.gradle
No
Issue #2695, a problem with the upcoming version of react-native. This should also work with all previous versions of RN.
- Use a RN 0.58.x project with react-native-webview which works fine.
- Update RN to 0.59.0-rc.2. This new version has some other gradle depencies and use Android 28 as build tool. Some other changes are also required, a [complete diff is available here](https://github.com/jerolimov/react-native-init-history/compare/0.58.3...4daf7fe0a996259aca633e17ad6747ae33dc1308).
- The build breaks with only updating RN.
- The build works again with applying this change. (My project uses supportLibVersion = "28.0.0")
You can test it with your project by installing this branch directly from GitHub:
`npm install --save "react-native-maps@jerolimov/react-native-maps#fix-rn59rc-compi …
> Enable RN projects to define the Android AppCompat Library version (and fix dependency issues with RN 0.59 RC)

- lib/ios/AirMaps.xcodeproj/project.pbxproj
- lib/ios/AirMaps/AIRMapManager.m
- lib/ios/AirMaps/AIRWeakMapReference.h
- lib/ios/AirMaps/AIRWeakMapReference.m
- lib/ios/AirMaps/AIRWeakTimerReference.h
- lib/ios/AirMaps/AIRWeakTimerReference.m
This PR fixes a memory leak on iOS using Apple Maps where AIRMap didn't get deallocated if the component is unmounted during an regionChange animation.
No
Didn't file an issue for it and haven't found one.
I did test it on the iPhone 8 Simulator and on a real iPhone 7 device.
Steps to reproduce: 
1. Create a simple Test App where you can mount and unmount the Map Component.
2. Mount the Map component
3. Change the region of the map animated, e.g. by calling: `animateToRegion`
4. Make sure that `- (void)mapView:(AIRMap *)mapView regionWillChangeAnimated:(__unused BOOL)animated` gets called. This method did cause the leak.
5. Unmount the Map component during the animation, this means before `- (void)mapView:(AIRMap *)mapView regionDidChangeAnimated:(__unused BOOL)animated` did get called. …
> Fix Memory Leaks on iOS

- index.d.ts
No.
With TypeScript, trying to use the Marker's icon property results in an error, since the `index.d.ts` does not yet declare the property that was added in #2650.
Tested by editing the `index.d.ts` locally. Since there are no functional changes, this is a trivial change.
> Add Marker icon property introduced in #2650 to index.d.ts

- docs/mapview.md
When using the setMapBoundaries method, it is not immediately clear why the user is able to scroll past the specified boundaries. Noting that the method uses the maps center coordinates would help clarify.
No, there are no other pull requests open on this issue.
Clarifies the use of the setMapBoundaries method.
No testing needed for markdown edits.
> Add clearer notes to setMapBoundaries method

- lib/android/build.gradle
This fixes a build error seen in app projects if the properties are not set.
I missed to include this in #2720
The gradle-maven-push.gradle script is only needed when publishing artifacts to a maven repository. It is *not* needed for apps consuming the library (and should not be included).
No
Issue reported by @grifotv in #2720
- Create a new project using `react-native init` and follow `react-native-maps` integration steps
- Use different dependencies in `package.json`:
| Dependency | Result |
| -- | -- |
| `"react-native-maps": "^0.23.0"` | ✔️ Success |
| `"react-native-maps": "react-native-community/react-native-maps"` | 🔴 Failure |
| `"react-native-maps": "friederbluemle/react-native-maps#fix-gradle-build"` | ✔️ **Success** |
> Include gradle-maven-push only when props are set

- lib/components/MapView.js
https://github.com/react-native-community/react-native-maps/pull/2671/files
As mentioned in https://github.com/react-native-community/react-native-maps/issues/2620, there are some YellowBox warnings with deprecated `UIManager` calls being used. The PR above fixed some of the warnings, but a warning still pops up regarding `AIRMapLite` and `AIRMap`.
- Updated iOS application that uses `react-native-maps` to `react-native@0.58.0`
- Open screen with any `MapView` component
- Check that no warnings regarding deprecated `UIManager` usage exists
> Fix deprecated UIManager usage when accessing component names

- lib/android/build.gradle
No
Some people have reported dependency issues with the Android support libraries (see #2695, #2720). The reason is a version conflict that Gradle alone can't resolve. Without explicit declaration, Gradle will use the transitive dependency (`26.0.1` from `play-services-base:16.1.0`). By explicit declaration it is possible to use other versions too.
This PR adds back the `appcompat-v7` dependency (even though the library has no dependencies on it) which was removed in #2720
Also (re-)added the conventional `safeExtGet` function seen in many other RN library projects.
Tested using the example project.
Step 1: Remove `appcompat-v7` dependency from example (The project has no dependency on `appcompat-v7`!)
Step 2: See project build fail. The reason is RN `0.54.2` which has a compile …
> Add appcompat-v7 dependency declaration to lib

- build.gradle
- lib/android/build.gradle
No
Allows the `play-services-*` dependencies versions to be set externally again. Something that was accidentally removed in #2720 
Version defaults to `16.1.0`.
Building the sample app, and changing the version.
> Android: Allow setting of play-services version through ext

- lib/ios/AirMaps.xcodeproj/project.pbxproj
No
When using Apple maps and CalloutSubview, the following error happens.
It seemed that CalloutSubview was added but the probject file wasn't updated.
I tested this PR with Apple maps on iOS in a simulator.
> [iOS] Fix CalloutSubview on Apple maps

- example/examples/DefaultMarkers.js
No.
No related issue.
The previous randomColor function may return invalid color string, like "#12345", which length is not valid. This may generate warning messages in the example page.
The new one fills the string with zeros, like "#012345" in the previous example.
I use this function to generate many colors randomly, and check if every color string is valid.
After the change, when I click many times to add markers to the map, the warning no longer appears.
> fix func 'randomColor' in DefaultMarkers.js

- example/App.js
- example/examples/MassiveCustomMarkers.js
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java
Looks No.
Android app's memory usage climbs high when there are thousands of markers on the map, even though most of the markers uses same image and the images are only around 1KB.
This update is to use a shared image icon for markers when they share the same image URI, instead of loading and creating bitmap within each marker, which uses more memory in case we have a lot of them.
Ideally you should test it with an app that contains a lot of custom markers that shared a small image pool.
To make it simple, we have also created a new page in example app, named "MassiveCustomMarker", which will place 100 custom markers on tap on the map. You can check it out and run the example app. Open android studio profile and watch the memory usage before and after the update while placing more markers …
> Marker share icon image

- lib/ios/AirMaps/AIRMapManager.m
No
#1163 
1. Add 2 `<Marker>`'s to a MapView, one with an `image={}` prop, one with subviews.
2. Call `takeSnapshot` on MapView.
3. Both annotations should exist on the generated image.
This has been tested on iOS device and simulator.
> Handle annotations without images on iOS map snapshot

- example/ios/AirMapsExplorer.xcodeproj/project.pbxproj
- example/ios/Podfile.lock
- react-native-google-maps.podspec
- Bumps Google Maps pod SDK to the latest version.
- Update example app
Replaces https://github.com/react-native-community/react-native-maps/pull/2753
Closes: https://github.com/react-native-community/react-native-maps/pull/2748
> [GoogleMaps] Update podspec to use GoogleMaps 3.0.3

- lib/ios/AirGoogleMaps/AIRGoogleMap.m
Address memory leak issues reported in https://github.com/react-native-community/react-native-maps/issues/2782 and https://github.com/react-native-community/react-native-maps/issues/2775
Following up from https://github.com/react-native-community/react-native-maps/pull/2581
> [AIRGoogleMap] Free instance variable in getActionForTarget

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
No PR do same thing is stalled
Cannot load base64 encoded image to Marker component on android
- tested on real device with android version 7.0
- ios not tested
> add support for loading base64 encoded image

- lib/components/MapView.js
Previously, the library would not pass on the updated style to native Google Maps if a change occurred after onMapReady had fired. The native side doesn't seem to mind this happening, although I did not test extensively.
> Update the Google Maps custom map style if changed after initialization

- react-native-google-maps.podspec
No other PR does the same thing
It fixes a error that occurs in react-native-google-maps 3.0.3 and not in 3.1.0
I tested it by changing the node modules in my project and the bug was fixed
iOS (android the bug did not occur)
on simulator
> Update google maps pods to 3.1.0

- lib/components/MapView.js
No
Resolves React warning being displayed when the `region` prop in `MapView` is `undefined`.  React requires a snapshot value (or null) to be provided (see warning message below).  This PR modifies `getSnapshotBeforeUpdate` in `MapView` to return `null` if `props.region` is `undefined`.
Change is JS only and only affects library's interaction with React.  However, the change was also tested on Android (on device) and iOS (device and simulator) to confirm warning is no longer triggered.
Steps to recreate and test for change:
1. Create `MapView` without `region` prop defined, e.g.:
```
<MapView style={{flex: 1, width: '100%'}} />
```
2. Run react native app and observe React warning in debug mode.
3. Now test with changes in this PR, warning should disappear.
> fix: resolves react snapshot undefined warning

- lib/components/MapView.js
no
In certain scenarios when custom map styling is applied, `getSnapshotBeforeUpdate` will try to apply custom styling using `this._updateStyle()` before Google Maps is instantiated on the native side.  This results in a crash on the native side as it's trying to set a property to the map which doesn't (yet) exist:
This PR adds a check in `getSnapshotBeforeUpdate` to confirm the map is ready (`this.state.isReady`) before applying a custom style.
During testing, this crash was only seen on Android.  But there's no reason why it won't also occur on iOS, I just haven't seen it happen.
It's hard to reproduce the exact circumstances when this crash occurs since it's a race condition between the native side instantiating the Google Maps library and the React/JS side triggering a `render()`.  It …
> fix: map style being set before map is ready

- lib/android/build.gradle
No current PR has this change, it solves the androidX migration without having to migrate this package.
fixes #2940 
Simple dependency change `compileOnly` fails for android 60 that is using jettifier post install script.
Changing to implementation fixes the build problem and runs as before RN 0.60
> Fix build gradle to allow jettifier to run correctly

- lib/ios/AirMaps/AIRMapMarker.m
No.
Call showCallout on a marker doesn't really select it.
Steps:
1. Add a draggable marker.
2. Call ```this.marker.showCallout();```
3. Hold the marker to start dragging, marker doesn't move and callout pop up again.  ❌
4. Hold the marker again, now it becomes draggable
This PR is for iOS, tested on both real device and simulator.
Steps:
1. Add a draggable marker.
2. Call ```this.marker.showCallout();```
3. Hold the marker to start dragging, marker turns into drag mode immediately
> fix select annotation when show/hide callout view

- package.json
- react-native.config.js
NO
-  according to the [react-native cli docs](https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide)
> remove "rnpm": {} in package.json
> moving the config into new file "react-native.config.js"
- Tested on real device & simulator
> convert to new react native config format (RN 0.60

- README.md
- docs/geojson.md
- example/App.js
- example/examples/Geojson.js
- index.js
- lib/components/Geojson.js
No
None
Tested on Android Real Device
I think that the less dependencies the better and GeoJSON support should be by default in this package.
```
import React from 'react';
import MapView, {Geojson} from 'react-native-maps';
const alcatraz = {
type: 'FeatureCollection',
features: [
{
type: 'Feature',
properties: {},
geometry: {
type: 'Point',
coordinates: [-122.42305755615234, 37.82687023785448],
}
}
]
};
const Map = props => (
<MapView>
<Geojson geojson={alcatraz} />
</MapView>
);
```
> Added GeoJSON support by default

- docs/installation.md
Not that I could find
This project's build.gradle files are using `playServicesVersion` ([1](https://github.com/react-native-community/react-native-maps/blob/4ee5d78ced9e3974a316e83703fc7e8023c497f8/build.gradle), [2](https://github.com/react-native-community/react-native-maps/blob/62bb953c19e55adb29200ecff9981eb5e594a7b3/lib/android/build.gradle#L24)), but the docs suggest setting `googlePlayServicesVersion` ([3](https://github.com/react-native-community/react-native-maps/blob/69e2f2582ef9ae49898f715e4f5940e17cdbc5ef/docs/installation.md#build-configuration-on-android)).
> Fix playServicesVersion name in Android installation docs

- docs/overlay.md
- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlay.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlayManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapOverlay.js
No
Adds `onPress` callback and `tappable` prop to `Overlay` on Android.
Fixes the issue that the MapView onPress events are getting swallowed by Overlays.
Tested with emulator and physical device on Android.
Add onPress callback handlers to the overlay and the MapView. 
With `tappable` set `true` the callback of the overlay fires as expected. With `tappable` set `false` the callback of the MapView fires.
> Add Overlay onPress event for Android

- example/ios/Podfile.lock
Nope
Unable to compile example with podfile.lock dependencies. Returns the error
```
[!] CocoaPods could not find compatible versions for pod "GoogleMaps":
In snapshot (Podfile.lock):
GoogleMaps (= 3.0.3)
In Podfile:
GoogleMaps
react-native-google-maps (from `../../`) was resolved to 0.25.0, which depends on
GoogleMaps (= 3.2.0)
Specs satisfying the `GoogleMaps, GoogleMaps (= 3.0.3), GoogleMaps (= 3.2.0)` dependency were found, but they required a higher minimum deployment target.
```
Ran it on the ios simulator and it compiled successfully
> updating pods for compile error

- lib/ios/AirMaps/AIRMapManager.m
Previous work has been done in #2692 - where this was extracted from - and #2314. 
The previous PR, while good, has been open since February and has seen no activity lately. Also, there are some concerns regarding the API it defines, where `onZoom`, `onPinch` etc could be a better alternative. 
This PR is a much narrower scope than the previous one, and should be simpler to get merged. It also presents no conflict if the former one would get merged.
Allows `onPanDrag` to be used while scrollEnabled is true, which is currently not supported. This seems like the best entry point for determining when the user has interacted with the Map. There are multiple requests relating to this requirement; #2756 #1038 #1620 (last not explicitly the same - but seems like the same base issue).
Also, …
> Allow using onPanDrag while scrollEnabled=true

- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
As far as I can see, no.
None actually. I was going to create one though, but it appeared that it would be easier to fix it myself. The thing is -- I am using `onUserLocationChange` listener in my app to get user's location, but I also need `heading`, and somehow it wasn't there.
But in comments of PR #2889, this also was requested.
I did it only with iPhone simulator. I added the listener to my map and then was setting `camera` property on it depending on the `heading` I get from the listener. It worked perfectly.
I probably gonna test it on a real android device at least, just don't have an opportunity to do it now.
> Add heading to the onUserLocationChange listener

- react-native.config.js
NO
No PR like this exists. It solves the issue of AIRMAP not found error while building on android screen.
"AIRMap" was not found in the UIManager IN "0.26.0"
https://github.com/react-native-community/react-native-maps/issues/3099
I tested the PR using the react-native-maps on my real time project on real devices android and iOS
> "AIRMap" was not found in the UIManager IN "0.26.0"

- lib/android/build.gradle
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
`react-native 0.60.5 - package android.support.v4.content does not exist`
> rn 0.60.5 support

- lib/android/build.gradle
Not that I can see
In 801614efcdca00fa2dbad89fca6af1607b4184e1 support for react native 0.60.5 was added, however it didn't safely check if `supportLibVersion` was set, which broke my build. A simple change like this fixed this issue.
Commit message:
```
This change makes sure that we safely check to see if supportLibVersion
is set before we try to use this.
```
Before this change nothing would build, but with this change it builds just fine.
> Add supportLibVersion safeguard in gradle build

- lib/ios/AirMaps/AIRMapManager.m
No
When taking snapshot, it used default mapType. This PR will keep the current mapType then take snapshot
Test in iphone simulator
> keep current mapType when taking snapshot

- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m
- lib/ios/AirGoogleMaps/AIRGoogleMapOverlay.m
- lib/ios/AirMaps/AIRMapMarker.m
- lib/ios/AirMaps/AIRMapOverlay.m
No
#3094 
I tested on a new react native project running on version 0.61.2 and observed that the deprecation warnings no longer appear after implementing the `moduleForClass` API and tested to make sure that Marker and Map overlay images load correctly after API changes
> replaced deprecated bridge.imageLoader calls with moduleForClass API

- docs/mapview.md
Line break types for "paddingAdjustmentBehavior" to decrease type-column width which increases Note column width. It was hard to browse props when Prop and Note columns were not visible at the same time (due to horisontal scroll in table and hidden overflow).
No.
It was hard to browse props when Prop and Note columns were not visible at the same time (due to horisontal scroll in table and hidden overflow).
Checked the preview tab on GitHub.
> Wider Note column (prevent horisontal scroll)

- lib/ios/AirMaps/AIRMap.m
No
#3100 
MapView went black in iOS (apple map) with `cacheEnable` when switching to other apps or goes to background
Local test on my phone.
Step 1. Open mapview with cacheEnable
Step 2. Switch to other apps then switch back -> mapview still visible
Step 3. Hide app to background then open again -> mapview still visible
> only handle cacheEnable when app is active

- lib/components/AnimatedRegion.js
I searched and didn't find any open PRs relating to `AnimatedRegion`
https://github.com/expo/expo/issues/4574
https://github.com/facebook/react-native/issues/25224
Locally in an Expo SDK 35 project. Step-by-step testing: initialize a project with the following code 
```
import React, { Component } from "react";
import { View, Text } from "react-native";
import MapView, {
AnimatedRegion,
Animated,
Marker,
MarkerAnimated
} from "react-native-maps";
export default class Test extends Component {
constructor() {
super();
this.state = {
coordinate: new AnimatedRegion({
latitude: -33.07204,
latitudeDelta: 0.01,
longitude: -68.98632,
longitudeDelta: 0.005622188905547227
})
};
// without these lines works well
}
async componentDidMount() {
const listener = this.state.coordinate.addListener(value …
```
> fix: AnimatedRegion.addListener() property setting

- index.d.ts
These types are inline with the `propTypes` in `lib/components/MapUrlTile.js`
Not that I can see, but if #2877 goes ahead, then the change might need to be made elsewhere as well. FWIW I prefer the typedefs here, rather than having to install yet another `@types/...` package.
typescript & IDE complaining about missing types
I didn't. I made this edit directly in GitHub
> Add missing MapUrlTileProps to index.d.ts

- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m
- lib/ios/AirGoogleMaps/AIRGoogleMapOverlay.m
- lib/ios/AirMaps/AIRMapMarker.m
- lib/ios/AirMaps/AIRMapOverlay.m
No
`RCTImageLoader` no longer works in iOS builds for RN>0.61.0. You need to use `RCTIMageLoaderProtocol` instead.
By successfully building the project after these changes were made.
1) Create a RN0.61.0 project
2) Link react-native-maps
3) Try to build iOS
> iOS Fix: Use RCTImageLoaderProtocol for ReactNative v0.61.0

- docs/marker.md
- lib/components/MapMarker.js
- lib/ios/AirMaps/AIRMapMarker.h
- lib/ios/AirMaps/AIRMapMarker.m
I couldn't find any PRs that add an always selected option on a marker (iOS). 
It adds a property to the `<Marker />` component called `isAlwaysSelected` which when set to true, allows a user to drag a marker immediately without having to first select it - similar to Android behaviour. This feature is useful when you want the ability to quickly drag markers rather than tap and then drag.
Affects iOS only.
Tested on the latest version of react native - 0.61.2 on simulator and real device
> add marker property isAlwaysSelected on iOS

- lib/components/AnimatedRegion.js
A previous (merged) PR addressed this same issue, but I think it introduced a new issue that should be resolved now. https://github.com/react-native-community/react-native-maps/pull/3131
Currently, on master (dd2a10d24de4bf398ccc445c08656647fcd33373), `AnimatedRegion.removeListener` does not work. This PR should make both `AnimatedRegion.addListener` and `AnimatedRegion.removeListener` work as intended again.
I described the issue more in a comment here: https://github.com/react-native-community/react-native-maps/pull/3131#issuecomment-543596374
I tested the functionality manually using RN 60 and react-native-maps on master + my commit.
I asserted with `console.log`s that the listeners are unregistered and deleted properly when calling `removeListener`, and that the listeners still …
> fix: AnimatedRegion.addListener / removeListener

- lib/ios/AirMaps/AIRMapOverlay.m
- lib/ios/AirMaps/AIRMapOverlayRenderer.m
No
The _mapRect generated from the MKMapRectMake() method was returning a negative height. This caused an invalid boundingMapRect, causing clipping of the overlay. The problem seems more pronounced on iOS 13.
possibly https://github.com/react-native-community/react-native-maps/issues/2801
iOS AirMap only. Tested on real device and simulator.
Problem seems more pronounced on iOS 13.
Create clean react-native project, using latest react-native-maps. Add overlay with bounds within north/west hemisphere. Zoom into the overlay. Clipping should not happen and full overlay should be displayed in the correct location and size.
Was not tested in any other hemisphere.
> Corrected issue with _mapRect calculation causing negative height and Overlay image clipping.

- index.d.ts
The optional iOS Google Maps prop is missing from the TypeScript definition file.
No
TypeScript definition for MapViewProps
TypeScript error about `paddingAdjustmentBehavior` missing on MapView went away.
> Added paddingAdjustmentBehavior to MapViewProps TS def

- docs/installation.md
No
#1947
When submitting to app store
```
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. 
The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. 
Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. 
If you're using external libraries or SDKs, they may reference APIs that require a purpose string. 
While your app might not use these APIs, a purpose string is still required. 
You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. 
Learn more …
```
> Add installation instruction about NSLocationWhenInUseUsageDescription

- docs/installation.md
This just applies the same change to the installation instructions as
this PR did for the example project's Podfile:
https://github.com/react-native-community/react-native-maps/pull/1718
I don't think so.
No issue seems to have been filed about that.
Self-evident, I guess.
> Fix iOS installation instructions for legacy RN versions

- example/android/app/build.gradle
- example/examples/ViewsAsMarkers.js
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarker.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapMarkerManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
NO
https://github.com/react-native-community/react-native-maps/issues/2633
Use the example page  [Arbitrary Views as Markers] , wait a little time, and tap the bear marker
> android google map callout support <Image/>

- lib/components/MapPolygon.js
Taking https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-522968087 as a reference. Apply `fillColor`, `stokeColor` and `stokeWidth` to polygons after the layout is calculated. 
A few related issues (https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-522968087, https://github.com/react-native-community/react-native-maps/issues/2867#issuecomment-573739457 ) were brought up and some comments indicated some temporary fix. However, no PR was found.
This issue was found while testing GeoJSON. In `Geojson` component, I passed in multiple style related props, `fillColor`, `strokeColor`, and `strokeWidth`. However, in iOS simulator, I could only see the default style (purple with opacity) being applied when using Google maps. …
> #3025 Fixes for polygon custom styles (fillColor, stokeColor, stokeWidth) not being applied on iOS devices when provider is Google maps.

- docs/overlay.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlay.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlayManager.java
- lib/components/MapOverlay.js
- lib/ios/AirGoogleMaps/AIRGoogleMapOverlay.h
- lib/ios/AirGoogleMaps/AIRGoogleMapOverlay.m
- lib/ios/AirGoogleMaps/AIRGoogleMapOverlayManager.m
No.
We needed the ability to control the transparency/opacity of Overlay components. For some reason, the transparency control for GroundOverlay was commented out for [Android](https://github.com/react-native-community/react-native-maps/blob/master/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapOverlay.java#L53) and was never implemented for iOS.
The `transparency` option was implemented as `opacity` as the rest of this project seems to prefer `opacity`, and both platforms implemented it differently as well.
Tested on an android emulator and iOS simulator using `react-native@0.61.0` and using the branch HEAD `"react-native-maps": "git://github.com/Crop-R/react-native-maps.git#5ee80e8d1e5af9962937d5db578d333fef4d35cb"` as a dependency. We pass an image url to the `image` …
> Implement opacity prop for MapOverlay on Android and iOS (Google Maps)

- lib/android/build.gradle
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
No.
#3282 and #2923
Set up a test RN project with my fork as a dependency, exported bundled APK to a OnePlus 6 and went outside for a walk. Compared user location continuosly with the Google Maps app.
**Note 1** 
When I try to run *example-android* it fails with the following error. However, when I add my fork to a test RN project it builds fine. I have not succeeded identifying the cause.
```
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
Suggestion: add 'tools:replace="android:appComponentFactory"' to …
```
> Fixed fused location source

- index.d.ts
- lib/components/MapView.js
No
#3185 
And also an issue i had personally when importing in a typescript project
I tested in my project, it's a react native + typescript app, the Geojson component can now be imported without giving any warning/error.
> Geojson component: exported and added types definition

- lib/components/Geojson.js
No.
This PR adds the ability to pass an image as props to a Geojson component. Thus, the image used for geojson markers can now be customized.
Related to this issue: https://github.com/react-native-community/react-native-maps/issues/3450
Tested on both Android and iOS simulators.
> feat: add the ability to pass a Marker image as Geojson prop

- lib/components/AnimatedRegion.js
No
When using React Native v0.62, a consistent warning will generate when using an animated region and animated marker. The warning (seen below) can be suppressed on iOS by setting the option `useNativeDriver: false` in `AnimatedRegion.js`.
[Issue](https://github.com/react-native-community/react-native-maps/issues/3483)
Warning: `Animated: 'useNativeDriver' was not specified. This is a required option and must be explicitly set to 'true' or 'false'`
I created an animated marker and then used an animated region when generating the coordinate. I then ran the build on my iPhone 11 Pro Max using xcode on iOS 13.5. The warnings that used to pop up no longer popped up.
> Added 'useNativeDriver: false' to Animated.timing to suppress warnings in React Native v0.62

- docs/installation.md
No
Adding instructions in `installation.md` about where to find the latest `androidMapsUtilsVersion`.
I found the answer here: https://stackoverflow.com/a/59795781/795820
> Added instructions about androidMapsUtilsVersion in installation.md

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
I have not found one.
Fix #3266
I did these changes in my own project where I used this module. Before this patch if I run `./gradlew check` I was getting the following error:
```
Errors found:
/Users/norbertschuler/Development/PFTP/treecounter-app/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java:421: Error: Must be one of: PermissionChecker.PERMISSION_GRANTED, PermissionChecker.PERMISSION_DENIED, PermissionChecker.PERMISSION_DENIED_APP_OP [WrongConstant]
return checkSelfPermission(getContext(), PERMISSIONS[0]) == PackageManager.PERMISSION_GRANTED ||
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/norbertschuler/Development/PFTP/treecounter-app/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.ja …
```
> Fix linting error when running ./gradlew check

- docs/examples-setup.md
Nope! 
This is just improving the documentation to build the example app for iOS. I needed to install `bundler:1.17.2` instead of just the latest version, so I thought it would be good to add that.
No testing necessary
> Specify needed bundler version in example instructions

- README.md
I checked with 0.63.+ it was not working,, after removing `_component` before  animateMarkerToCoordinate working for Android. For more info have a look https://stackoverflow.com/a/63897282/3026578
NO
[Cannot read property 'animateMarkerToCoordinate' of undefined](https://stackoverflow.com/questions/61740171/cannot-read-property-animatemarkertocoordinate-of-undefined/)
after updating my project to latest react native version animateMarkerToCoordinate for Android stop working before it is working fine with recat-native version 0.61.+ . After removing _component before animateMarkerToCoordinate it is working fine now
> animateMarkerToCoordinate of undefined

- lib/ios/AirGoogleMaps/AIRGoogleMapMarker.m
No.
Fixes warning:
```
Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
```
Manually Tested.
> Prefix call w/ self->

- docs/mapview.md
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/android/src/main/java/com/airbnb/android/react/maps/RegionChangeEvent.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMap.h
- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.h
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
There is a PR that solves likely the problem #2935, but with a workaround.
The problem we are trying to solve is to know the reason when the region has changed on the map.
Using `onPanDrag`, implemented by the PR #2935, is a non stable workaround. Because will would have to first store somewhere a boolean on the `onPanDrag`, and use it once `onRegionChangeComplete`.
Issue #1620 and #2756.
I implemented and tested (on a real device) the code for android. The iOS part too has been implemented by my friend. And was tested on an emulator.
> Pass camera move's reason to JS callbacks

- lib/android/src/main/java/com/airbnb/android/react/maps/ImageReader.java
Same as this PR https://github.com/react-native-maps/react-native-maps/pull/2392 in AirMapMarker
No PR do same thing is stalled
The ability to add base64 images in modules using ImageReader, such as Overlay
- Tested on real device with Android 7.1.1
> Load base64 encoded image in ImageReader

- docs/geojson.md
- lib/components/Geojson.js
No, there is no another PR to add this functionality.
#3491 
- Tested on both Android and iOS Platforms with Google API key.
- I've tested this on both in real device and a simulator.
This simply adds the `zIndex` prop for the `Geojson` component. It lets developers to use multiple Geojson into each other.
> Added zIndex prop on Geojson

- index.d.ts
No
It allow typescript to import the `Animated` export. Without it - anyone using typescript won't be able to import the `Animated` export.
As this change is only applied on the typescript definition - no test is necessary on the functionality of this plugin. 
But you can test the typescript support by simply importing the `Animated` export and transpile using TSC command. Which will allow the typescript import without any issue. 
Tested on latest stable Typescript 4.0.3. Also tested the code working by running the app on a Android device on debug mode.
> TypeScript Fix: Renamed invalid export type MapViewAnimated to Animated

- lib/components/MapView.js
No previous PR
it fixes the duration, because whenever i pass {duration: 0} to animateCamera it always default to 500
Tested in Android Devices/Emulators
> animateCamera duration bugfixed

- docs/geojson.md
- lib/components/Geojson.js
No
The GeoJson feature of this library does not preserve the stroke width, stroke color, fill color, and marker color properties from the GeoJson supplied. This PR now preserves all those properties and successfully displays map elements with those styling properties. 
While these two issues may not be specifically about GeoJson, much of comments are about the GeoJson styling issue:
#2867 #3057
This PR was tested with Android and iOS simulators, although the same logic was tested in a patch on real iOS and Android devices. 
Using a GeoJson creator like [https://geojson.io/](https://geojson.io/) - it is easy to create map elements with properties in the GeoJson. From there, it's just a matter of firing up an app that uses the GeoJson you created in a map view.
> Geojson stroke color, stroke width, fill color, and marker color properties preserved

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
fix crash when double tap on a not initialized map view
No.
#3653 
return if map is null in doubeTap's handler
> fix crash of double tap

- CHANGELOG.md
As discussed #3706 updated the change log. I haven't added the date of release.
> Update changeLog for version 0.28.0

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
No, no other PRs deal with Camera Zoom. 
It is fixing issue #3725 on Android devices. It is pretty simple. 
* I tested this PR in my own little project. The fix is so minimal that I didn't really see it necessary to create an online sample. If you'd like me to make a sample code, I'd happily do it.
* It's tested on a Google Pixel 4a phone. 
* I haven't tried iOS, this wouldn't affect iOS anyways.
> Android - Use double on `setCamera` to fix zoom precision. 

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
NO
#3308 
Just verify it by following steps : 
1. Set mapPadding to the `MapView` in `example/examples/FitToCoordinates.js:69`, such as 
```
<MapView
...
mapPadding={{ left: 15, top: 0, right: 0, bottom: 60 }}
...
>
```
2. Run the demo app from this PR on Android
3. Enter `Fit Map To Coordinates`, you can see the Google watermark is located with padding.
4. Click Btn `Fit Bottom Two Markers with Padding`
5. Camera zooms in those two Markers while Google watermark keeps in the same position instead of moving to the initial pos.
6. Problem solved
> Android:Fix fitToCoordinates with preset mapPadding (#3308)

- index.d.ts
No previous PR
It fixes a missing typing. The onRegionChange and onRegionChangeComplete event handlers receive a second parameter, which appears in the docs and the source code but not in the typings.
N/A - I read the docs, saw the typing was gone, looked at the source code, saw the docs were ok but the typings were not and fixed these. 
Just code review would be sufficient.
> Fixed missing typing

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
No
#3308 relevant
The adding edgePadding in fitToCoordinates method hasn't been considered the unit before.
Need to change apply the density which is changing from DP to px.
When setting `edgePaddingTop=200` in a `MapView` which has `mapPaddingTop` 200 already.
Before 
After 
To verify this change, apply edgePadding and mapPadding as follow. 
```
this.map.fitToCoordinates([MARKERS[2], MARKERS[3]], {
edgePadding: { top: 200, right: 0, bottom: 0, left: 0 },
animated: true,
});
```
```
<MapView
ref={ref => {
this.map = ref;
}}
style={styles.map}
initialRegion={{
latitude: LATITUDE,
longitude: LONGITUDE,
latitudeDelta: LATITUDE_DELTA,
longitudeDelta: LONGITUDE_DELTA,
}}
mapPadding={{ left: 0, top: 200, right: 0, bottom: 60 }}
>
```
> Fix fitToCoordinates edgePadding unit (#3308)

- docs/mapview.md
- example/examples/MapKml.js
- index.d.ts
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapManager.java
- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
- lib/ios/AirMaps/AIRMapManager.m
There is no previous PR which does the same thing. 
The method fitToElements does not support edge padding. 
It should have the same api as fitToSuppliedMarkers and fitToCoordinates.
We have tested the changes on iOS and Android using physical devices on both platforms. 
These changes only affect Google Maps and not Apple Maps, as I've also clarified in the readme. 
You can test the new functionality by passing edgePadding to the fitToElements function and see how the markers are no longer aligned with the very edge of the map. Instead it uses the provided padding.
> Add edgePadding support to fitToElements method.

- lib/ios/AirGoogleMaps/AIRGoogleMap.m
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.h
- lib/ios/AirGoogleMaps/AIRGoogleMapManager.m
No
See #3014
When there are multiple maps and one is removed the iOS app crashes on an indoor event.
Tested on a simulator. I rendered 2 MapViews and dynamically toggled the second while triggering and monitoring indoor events on both maps.
> Fix indoor events on iOS for multiple MapViews

- docs/installation.md
The current installation guide makes a lot of references to React Native <= 0.59. This release is very old now, and very few people will be installing react-native-maps from scratch in <= 0.59 these days. So I linked to the current version of the installation docs by commit sha and removed everything related to <= 0.59, plus did a bit of other random cleanup (eg: we mention npm and yarn install instructions, I think people can figure out how to install with yarn if they have already gone ahead and installed yarn).
No.
No open issue.
Set up react-native-maps on a new project.
> [docs] Clean up old installation instructions, organize a bit better

- lib/android/.npmignore
No, no other PRs exist that I saw
It was not logged. But I'm about to put a deprecation notice on the jetifier package and these files turned up as warnings, I thought I'd help you all get rid of them
On android if you use version 0.28.0, the gradle build runs jetifier and in the soon-to-be-release jetifier it emits warnings that this package has non-AndroidX files.
It turns out they are in `lib/android/build` which I thought was strange, but it appears the npm package step isn't ignoring them, so anyone might package them up when releasing
I maintain react-native-device-info and our android `.npmignore` file looks exactly like the one I propose here and has for quite some time - works great
https://github.com/react-native-device-info/react-native-device-info/blob/master/android/.npmignore …
> build(android): do not package android build directory

- index.d.ts
When using Typescript in strict mode, it fails with this error:
```
error TS2440: Import declaration conflicts with local declaration of 'Animated'.
```
It is caused by the typings importing `Animated` from `react-native` while defining a local `Animated` class.
Using an import alias fixes the issue.
No
None, I directly opened the PR instead of an issue
We are using this updated typings in our app and TS compiler is no longer complaining.
> Fix import/local conflict in typings

- index.d.ts
Enable to access setNativeProps method when using Circle ==> helpful for typescripters to counter the native props bug
https://github.com/react-native-maps/react-native-maps/issues/2698#issue-411737976
> enabling setNativeProps method export for Circle

- index.d.ts
No
Typescript definition file is missing informations such: 
- `action`
- `id`
Which are instead sent by AirMap bridge module when pressing inside the map. 
Using typescript would cause error at compile time even if the information is provided at run time.
Android/iOS with both Google and Apple Maps
> Include missing information on MapEvent definition

- index.d.ts
No
Missing type for onMapLoaded property. Useful for typescript users
> onMapLoaded missing type

- index.d.ts
If you use zIndex prop on `Geojson` component, you get typescript errors since it's not part of the declaration. 
No
I haven't seen an existing issue. I noticed this problem while working on my app.
I did this change on my project in node_modules and tried it out on iOS.
> Add zIndex prop for Geojson to type declarations

- docs/geojson.md
- example/examples/Geojson.js
- index.d.ts
- lib/components/Geojson.js
No other PR has the same thing
No issue right there, directly a fix and a new feature.
Tested on both iOS and Android with both simulators and real devices.
This PR fixes the `GeoJSON`'s onPress undefined crash fix.
---------
- GeoJSON has the default Marker for the `Point` however there are no `customization` options for the `GeoJSON`. Now it has the new prop option: `markerChildren` which receives any UI component for the new Marker Image.
Big yellow Point markers are the default one and we could not customize its style in any way. Small-green Point markers are the new `Image` or `FastImage` any other UI component which can be customized by the dev itself.
> GeoJSON onPress Crash Fix and Marker Customization Options

- react-native-google-maps.podspec
Bumps the GoogleMaps version and Google-Maps-iOS-Utils versions to fix dependency bugs happening.
See #3893. Should be tested for the breaking change in Google-Maps-iOS-Utils 2.1.0 -> 3.0.0.
should resolve #3893
No
[3893](https://github.com/react-native-maps/react-native-maps/issues/3893)
Not sure how to test this correctly. `GoogleMaps` 3.5.0 -> 3.7.0 does not have any noteworthy changes. `Google-Maps-iOS-Utils` 2.1.0 -> 3.0.0 has a breaking change of: [Change GMUFeature properties type from NSString to NSObject](https://github.com/googlemaps/google-maps-ios-utils/commit/4a562be73ddd6f7181428f1d71d8930322e559a0). But I am not able to find any reference to that code. So this should probably be reviewed by someone that has some insights into the code to determine if it can be merged or …
> chore(podspec): bump the gmaps and gmaps-ios-utils versions to 3.7.0 and 3.0.0

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/ios/AirMaps/AIRMapManager.m
No
There are some issues regarding the _onPress_ on a polygon that returns the wrong coordinates:
- **android**: the coordinates of the first vertex of the polygon are returned and not those of the point where I clicked
- **ios**: coordinates are not returned
With my fix it is now possible to have a homogeneous behavior for ios and android and therefore it is possible to have the coordinates of the exact point where I tapped inside the polygon.
Tested on both iOS and Android with both simulators and real devices.
> Fix: polygon on press wrong coordinates

- index.d.ts
[This line](https://github.com/react-native-maps/react-native-maps/blob/b27b82e23105a32dcae8d8e296251d55856b04c5/lib/components/Geojson.js#L132) assumes the existence of the property `features` on object passed to the `geojson` prop. But the `features` property does not exist for `Geometry` or `Feature` types, so TS thinks it's allowable to pass those types even though they will cause the app to crash
No
- https://github.com/react-native-maps/react-native-maps/issues/3974
Manually overwrote the `index.d.ts` file in `node_modules` and found that TS began (correctly) complaining if I tried to pass something other than a `FeatureCollection` in the `geojson` prop.
> Narrow GeojsonProps `geojson` prop to correspond to expectations

- __tests__/AnimatedRegion.test.js
- lib/components/AnimatedRegion.js
- package-lock.json
- package.json
- yarn.lock
No. This is a bug that arose as of the latest release, as identified in issue #4010. 
Prior to the latest release, `AnimatedRegion` handled determining whether a provided `value` was an instance of `Animated.Value`. If it was, we returned that value; if not, we created a new `Animated.Value` instance. The latest release presented a regression in that, rather than creating a new instance off the `valueIn` to `getAnimatedValue`, we instead used created a new `Animated.Value` using the supplied fallback.
Issue #4010 
This is more a bug fix that reverses a regression. However, pending approval and possibly further conversation, I've added a preliminary dev-only test setup to confirm `AnimatedRegion.js` changes work.
> Feature fix `AnimatedRegion` `getAnimatedValue` Issue #4010

- lib/components/Geojson.js
I don't think so. Although the proposed typescript re-write may supersede this change once merged
'tappable' prop type should be "bool" not "boolean". This mistake causes warnings in typescript projects. See https://www.npmjs.com/package/prop-types#usage
Modifying the line in my own project's node_modules/react-native-maps make the error go away
> Update Geojson.js 'tappable' prop type

- lib/ios/AirMaps/AIRMapManager.m
No.
This PR is a fix for #4031. Two `onRegionChange` events where getting called while the Apple map was first rendering. Found out where this events were being triggered, and added a check not to call them until the map starts rendering which fixes the issue.
Now Apple maps behaves the same as google maps.
Tested on an iPhone 12 simulator running iOS 15.0
> [ios] Fix: Apple Maps calling onRegionChange while the map renders

- lib/ios/AirMaps/AIRMapManager.m
No
#4053 
The change is very small, but it can be tested like this:
1. Create a map
2. Add a polyline
3. Press it, and log the event to the console
4. The event object should contain the coordinates of the first point in the polyline, like the behavior on Android.
This affects Apple Maps on iOS. I tested it on a simulator.
> [ios]: Add coordinates to Apple Maps Polyline onPress event

- index.d.ts
As suggested at https://github.com/react-native-maps/react-native-maps/issues/3906#issuecomment-933259986
No
#3906
Downloaded the sample code from the linked issue and uncommented the line that references __lastRegion. I get a TypeScript error in my editor that the field is supposed to be private, but I also see that Typescript is inferring the correct type for it.
> Add MapView.__lastRegion to index.d.ts

- package.json
No
Some license looking libs expecting to see a license field in the `package.json`
Run [lib](https://github.com/nodeshift/license-reporter) over my changes to find the MIT license.
> chore: add license to package.json

- README.md
It had the wrong kind of quotes. The old ones were not valid when copy-pasted.
> docs: fix readme code example

- lib/android/build.gradle
I failed at starting a discussion regarding #4080 so instead I'm opening this, with what I believe is a better solution (for now at least).
Doing a conditional upgrade allows anyone to update `react-native-maps` without requiring any changes, while also avoiding crashes in projects with `targetSdkVersion >= 31`.
Ideally, work should be put into testing whether the tile components works as expected with this new version, but I assume that a lot of consumers aren't using the tile components, and 'just' need their apps to not crash on Android 12. Either way, this change shouldn't leave anyone worse off than they are... :)
Implemented this change in `react-native@0.67` & `react-native@0.68` (`targetSdkVersion < 31` & `targetSdkVersion = 31`) projects, resulting in the expected `androidx.work` …
> fix(android): android 12 crash

- lib/components/Geojson.js
- lib/components/MapCallout.js
- lib/components/MapCalloutSubview.js
- lib/components/MapCircle.js
- lib/components/MapHeatmap.js
- lib/components/MapLocalTile.js
- lib/components/MapMarker.js
- lib/components/MapOverlay.js
- lib/components/MapPolygon.js
- lib/components/MapPolyline.js
- lib/components/MapUrlTile.js
- lib/components/MapView.js
- lib/components/MapWMSTile.js
- package.json
- yarn.lock
No.
`Image.propTypes`, `Text.propTypes`, `TextInput.propTypes`, `ColorPropType`, `EdgeInsetsPropType`, `PointPropType`, and `ViewPropTypes` from react-native are deprecated, and starting from react-native@0.68 using them will print a warning. They have already been removed in the main branch, so react-native@0.69 likely won't include them at all.
See: [react-native@0.68 changelog](https://github.com/facebook/react-native/blob/66419ed8f5be4e0efca4e0f261d902607408f29c/CHANGELOG.md#changed)
Suggested solution is to use the `deprecated-react-native-prop-types` package instead, which this PR does.
Installed react-native-maps in a react-native@0.68.0-rc.1 project, resulting in a lot of warning messages. After these changes, the warnings are no longer printed and the library continue to work as …
> feat: migrate to deprecated-react-native-prop-types

- lib/android/src/main/java/com/airbnb/android/react/maps/AirMapView.java
- lib/components/MapView.js
No.
#4060
Currently, initialRegion on Android takes a JS round trip after onMapReady before being set, which causes the issue described in #4060. This PR removes that round trip.
Tested on both a physical device and an emulator. I'm no longer able to reproduce #4060 after the change.
> fix(android): initialRegion delay

- docs/installation.md
- react-native-maps.podspec
No.
The deployment target in our podfiles got changed to 12.0 when the Google Maps SDK for iOS was bumped to 6.0 which dropped support for iOS 11. But it was changed in both the default podfile and the google maps podfile, meaning that a deployment target of >= 12.0 is required, even when not using Google Maps on iOS.
Installed and ran `react-native-maps` on iOS with deployment target 11.0 with Apple Maps only.
Installed and ran `react-native-maps` with the google maps pod on iOS with deployment target 12.0 with Apple Maps and Google Maps.
> fix(ios): pod install failing with deployment target 11.0

- src/Geojson.tsx
- src/MapCallout.tsx
- src/MapCalloutSubview.tsx
- src/MapCircle.tsx
- src/MapHeatmap.tsx
- src/MapLocalTile.tsx
- src/MapMarker.tsx
- src/MapOverlay.tsx
- src/MapPolygon.tsx
- src/MapPolyline.tsx
- src/MapUrlTile.tsx
- src/MapView.tsx
- src/MapView.types.ts
- src/MapWMSTile.tsx
- src/index.ts
- src/sharedTypes.ts
- src/sharedTypesInternal.ts
No
Many types are exported by the 0.31.1 of the library, but because we're now directly creating the `index.d.ts` from the actual Typescript, they're no longer exported.
This PR fixes this by:
1. Extracting all the types used by Props and callable functions into a `MapView.types.ts` and exporting those types
2. Exporting MapViewProps
3. Exporting all `sharedTypes.ts`
- I moved the helper type `Modify` into a `sharedTypesInternal.ts` that's not exported
4. Exporting all the Props and inner components. The inner component types are useful for `React.createRef` and `useRef`
This is a pure typing change with no functionality change. I tested this by:
1. Creating a build of the package and installing it using `yarn add wanderlog/react-native-maps#407b2526384c6336f00ae094b518a34db9164a2c`
2. …
> fix(types): export types that were present before v1

- docs/installation.md
- example/ios/Podfile
- example/ios/Podfile.lock
- react-native-google-maps.podspec
BREAKING CHANGE: Using Google Maps on iOS now requires iOS >= 13.0 and XCode >= 13
Description in commits.
> feat(ios-google): bump maps sdk to 7.0.0

- ios/AirGoogleMaps/AIRGoogleMap.h
initialCamera is accessed outside setter method, so property should have strong attribute.
Resolves #4321
> fix(ios-google): crash when setting initialCamera prop

- src/MapView.tsx
This was introduced in 08ffc4ac398b38e0efe7c4d8da52e56f924f028d but since findNodeHandle is unused
in MapMarker I'm not reverting the entire commit.
Resolves #4415
> fix(MapView): invalid parameter passed to nativemodule methods

- README.md
No.
[Existing link](https://developer.android.com/studio/write/image-asset-studio#access) to adding Android drawables points to adding Launcher icon, which is not what you want when adding images for markers. [This link seems](https://developer.android.com/studio/write/resource-manager#import) more accurate and helpful.
No testing.
> docs: improve README link to drawables

- android/build.gradle
- docs/installation.md
BREAKING CHANGE: drop support for overriding play-services-{base,maps} version
> feat(android): use semantic version range for gradle dependencies

- android/build.gradle
No
At Expo, we would like to bump the version of `gms:play-services-location` we use in `expo-location`. Doing this without bumping the version here will cause apps that have both libraries installed to crash.
`rnmshowcase` works as before. I went through the entire list of examples. Some of them have issues unrelated to the change in this PR.
> build(deps): bump play-services-location version

- android/build.gradle
No
As stated here https://github.com/react-native-community/discussions-and-proposals/issues/671 React Native 0.73 will depend on Android Gradle Plugin (AGP) 8.x and this will require all the libraries to specify a namespace in their build.gradle file.
Build on android using AGP 8
> feat(android): Add android namespace to support react-native 0.73

- docs/installation.md
- example/ios/Podfile
- example/ios/Podfile.lock
- example/ios/PodfileFrameworks
- react-native-google-maps.podspec
No
https://github.com/react-native-maps/react-native-maps/issues/4754
Tested on iOS from 13 to 16.5.1. 
App built on Intel and Apple Silicon machines.
> [iOS] Update Google-Maps-iOS-Utils to 4.2.2 to officialy support Apple Silicon without Rosetta

- ios/AirGoogleMaps/AIRGoogleMapMarker.m
Yes, [4824](https://github.com/react-native-maps/react-native-maps/pull/4824)
- the previous PR is stalled, as it's really old and the author didn't continue working on it
https://github.com/react-native-maps/react-native-maps/issues/4823
> fix: crash due casting

- src/MapView.types.ts
No
Use `number` types for `EdgePadding` type so typescript can correctly evaluate the types.
I don't think this PR needs testing.
> fix: EdgePadding types

- android/src/main/java/com/rnmaps/maps/MapView.java
No
Fixes https://github.com/react-native-maps/react-native-maps/issues/4891
* Affected platform: **Android** with **Google Maps**
* This PR was tested on a real device using [Flipper](https://fbflipper.com/) to verify the views are removed correctly
This is what happens without this PR. The included [example](https://github.com/krakowski/react-native-maps/blob/c3a4c4450057d3d9e437918056889a7c57f4611b/example/src/examples/BugMarkerMemoryLeak.tsx) should reproduce this behavior.
https://github.com/react-native-maps/react-native-maps/assets/7255767/46beb33c-e866-480e-baf9-8cda3ebc1e5c
> fix(android): remove dangling map marker views causing memory leak

- android/src/main/java/com/rnmaps/maps/MapMarkerManager.java
No
Wrong event type was being used for onSelect on android for MapMarker, it seems like since it's a common event name it should follow the same type implemented by other react-native components, in this case bubbling event.
[5030](https://github.com/react-native-maps/react-native-maps/issues/5030)
On an android device
> fix(android): onSelect was crashing android

- .github/workflows/androidBuild.yml
- android/build.gradle
- example/android/app/build.gradle
- example/android/gradle.properties
- example/babel.config.js
- example/ios/Podfile.lock
- example/ios/rnmshowcase.xcodeproj/project.pbxproj
- example/ios/rnmshowcase/AppDelegate.mm
- example/package.json
- example/react-native.config.js
- example/src/examples/AnimatedMarkers.tsx
- example/yarn.lock
- src/decorateMapComponent.ts
No
New arch will be turned on by default in RN 0.74, to prepare for it we need to have the example app running new arch and make it available so that library users can test and provide early feedback.
On a physical device for both android and iOS (MapKit)
todo: iOS GoogleMaps
> feat: Enable new arch for the example project

- ios/AirGoogleMaps/AIRGoogleMap.h
- ios/AirGoogleMaps/AIRGoogleMap.m
- ios/AirGoogleMaps/AIRGoogleMapManager.m
https://github.com/react-native-maps/react-native-maps/pull/5026/
Yes, but the approach is different, this one simply makes sure that there is no race condition when setting up the mapview.
https://github.com/react-native-maps/react-native-maps/issues/5024
Didn't, but this is a systematic approach so it should work
> fix: use initialProps to set zoomTapEnabled in google-maps-ios

- README.md
No
Clarify the warning message that says unstable_reactLegacyComponentNames is not necessary
Doc update, prettier passed
> chore(react-native): update docs

- android/src/main/java/com/rnmaps/maps/MapModule.java
- android/src/main/java/com/rnmaps/maps/MapUIBlock.java
No
Following APIs will be broken in Bridgeless mode after https://github.com/react-native-maps/react-native-maps/pull/4985 adds support for Bridgeless in React Native 0.74 on Android :
- takeSnapshot()
- getCamera()
- getAddressFromCoordinates()
- pointForCoordinate()
- coordinateForPoint()
- getMapBoundaries()
Since these [depend](https://github.com/react-native-maps/react-native-maps/blob/master/android/src/main/java/com/rnmaps/maps/MapModule.java#L93-L94) on `context.getNativeModule(UIManagerModule.class)`:
which returns null in Bridgeless
https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java#L600-L606
Test `takeSnapshot()` functionality for Android in Bridgeless
> fix(android): UIManagerModule fix for Bridgeless 0.74

- src/Geojson.tsx
No
Add missing props for polygon in the Geojson component. So I provided these props (lineDashPhase, lineDashPattern, lineCap, lineJoin and miterLimit) so an Geojson component with a polygon can also render a dashed line.
I have tested the change on iOS using an iPhone and in the simulator. For Android, this will not work because this is not implemented yet in Android.
> Implement dash options for geojson polygon

- android/src/main/java/com/rnmaps/maps/MapPolygon.java
- android/src/main/java/com/rnmaps/maps/MapPolygonManager.java
- src/Geojson.tsx
- src/MapPolygon.tsx
No
As mentioned in https://github.com/react-native-maps/react-native-maps/pull/5115, Android still does not support dashed lines. With this update, you can now use the lineDashPattern prop with both Polygon and Geojson components.
I have tested the change on Android using an Samsung phone and in the emulator.
> feat(android): add dash pattern for android (#5115)

- ios/AirMaps/AIRMapMarker.m
No.
#4996 
I have tested it on iPhone 15 Pro simulator(iOS 17.5) and iPhone 14 Pro(iOS 17.5.1).
(The issue occurs only iOS)
1. Specify an  onPress for a Marker on a iOS device.
2. Tap a marker and see the event.nativeEvent returns position as well.
In addition, this is a repository AirMapMarker.m file patched with patch-packager: 
You can also check it. [repro-on-marker-press](https://github.com/abdullahbayram/repro-on-marker-press)
> fix(iOS): ensure onPress(Marker) returns nativeEvent.position #4996

- ios/AirMaps/AIRMapMarker.m
No.
This PR is a follow-up to issue [#4996](https://github.com/react-native-maps/react-native-maps/issues/4996) 
In the initial fix, I mistakenly used `nativeEvent.point` instead of `nativeEvent.position`, which should have been used to ensure consistency with both the documentation and Android behavior.
I have tested it on:
- iPhone 13 Pro simulator (iOS 17.5)
- iPhone 14 Pro (iOS 17.5.1)
(The issue occurs only iOS)
1. Specify an `onPress` for a Marker on a iOS device.
2. Tap a Marker and verify that `event.nativeEvent `returns the correct `position` instead of `point`
> fix(iOS): Refactor onPress(Marker) to return nativeEvent.position for consistency with Android

- .gitignore
- react-native-maps-generated.podspec
No
having the generated pod visible via cocoapods trunk
not yet possible
> fix: simplified generated podspec to pass lint

- src/decorateMapComponent.ts
Yes, https://github.com/react-native-maps/react-native-maps/pull/5465
Fixes the TypeScript errors:
../../node_modules/react-native-maps/src/decorateMapComponent.ts:26:27 - error TS5097: An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled.
https://github.com/react-native-maps/react-native-maps/issues/5423
> fix: ts-import for decorateMapComponent

- android/src/main/java/com/rnmaps/maps/MapView.java
There is no other open PR doing the same thing.
https://github.com/react-native-maps/react-native-maps/issues/5513
I have created a patch for the package with this change in my own project and it fixed the issue I was encountering. The issue also links to a commit that was made for the rewrite for Fabric where these lines were apparently incorrectly changed.
> fix: correctly emit marker-press event for Android

- src/MapMarker.tsx
No
https://github.com/react-native-maps/react-native-maps/issues/5443
example project with all variation of provider (ios, ios-google, android)
> fix(ios): googleMaps marker images not visible

- android/src/main/java/com/rnmaps/fabric/MapViewManager.java
No
https://github.com/react-native-maps/react-native-maps/issues/5578
couldn't reproduce the crash but the logic is consistent, naked use of onDestroy causes NPE while use of the safe method doDestroy (checks for observers) solved other NPE caused by lifecycle before.
> fix(android): fix NPE crash on destroy

- .github/workflows/iosBuild.yml
- .github/workflows/iosFrameworksBuild.yml
Yes
https://github.com/react-native-maps/react-native-maps/pull/5702
I'm trying to keep change to minimum by only fixing the image version of the CI, so that we can use latest again once github release a fixed version of their action.
broken CI
How did you test this PR?
let's hope for a green iOS builds
> fix(ios): attempt to fix ci by pinning the macOS version

- .github/workflows/iosBuild.yml
- .github/workflows/iosFrameworksBuild.yml
No.
It removes pinning the macOS version on CI
let's hope for a green iOS builds
> chore(ci): set macos host to macos-latest to remove exact os vesrions pinning

- README.md
No
The README file lists 1.21.1 as the last supported version for the old architecture.
1.21.0 is the first version with Fabric support (and where the old architecture is no longer supported).
1.20.1 is the last version where the old architecture is supported
N/A
> fix: update versions for new/old arch support in README
